렌더별 파일 및 폴더 구분 저장
ACON3D/blender pull request #1
Opened 2022-03-29 07:39 UTC by habijung

## 문제
`General > Render` 기능 사용 시 파일명이 아닌 폴더 명으로 저장되는 문제 해결

## 수정 사항
- 파일 / 폴더 저장 구분을 위해서 `Acon3dRenderOperator` 의 하위 클래스로 `Acon3dRenderFileOperator` 와 `Acon3dRenderDirOperator` 로 구분
- `Acon3dRenderFileOperator` 는 문자열에 확장자 추가를 위해 `ExportHelper` 사용
- 마찬가지로 `Acon3dRenderTempSceneFileOperator` 클래스 추가하고, `Acon3dRenderTempSceneOperator` → `Acon3dRenderTempDirOperator` 로 변경한 이유는 상속받는 클래스 `ImportHelper` 와 `ExportHelper` 가 다르기 때문
- Panel 에 명시된 순서로 클래스 위치 조정

## 해결 사항
- Quick, Full, Line, Shadow → 파일로 저장
- All Scene, Snip → 폴더로 저장
- 파일 저장 시 현재 Scnen 이름 가져오기 (확장자 `.png` 포함)
- 폴더 저장 시 현재 Blender 파일 이름 가져오기 (확장자 제외)
- 저장할 때 파일 및 폴더 이름 변경 가능
- 임시 파일 `untitled` 에 대해서도 문제 해결

## 보완할 사항
- [ ] 무조건 `.blend` 파일 위치가 기준으로 file browser 가 시작됨. 마지막으로 저장한 위치가 시작점이면 좋을 것 같음
- [ ] 같은 문제로, 임시 파일 `untitled` 시작점은 `C:/.../Documents` 로 고정
- [ ] 단일 파일 저장되는 기능도 폴더로 저장 하는 기능 추후 고려

2022-03-29 08:02 UTC, habijung commented
모든 렌더 테스트 필요

2022-03-29 08:04 UTC, seungha-kim commented
(슬랙 알림 테스트)

2022-03-29 08:05 UTC, seungha-kim commented
(슬랙 알림 테스트2)

2022-03-29 08:07 UTC, seungha-kim commented
(슬랙 알림 테스트)

2022-03-29 08:50 UTC, Youdiie requested changes
코드양만 봐도 정말 큰 태스크였네요! 고생하셨습니다
코멘트로 남긴 추상클래스 구현만 부탁드림니다

2022-03-29 08:50 UTC, Youdiie commented on release/scripts/startup/abler/render_control.py
> +            self.filepath = "untitled"
맨처음 코니방에서 이름 없을때 untitled 넣어주군요!

2022-03-29 08:50 UTC, Youdiie commented on release/scripts/startup/abler/render_control.py
> +    def modal(self, context, event):
여기 modal이 실제론 Acon3dRenderDirOperator에 쓰이는거죠? 그러면 Acon3dRenderDirOperator 여기로 가고 modal은 비어두면서 추상클래스로 구현하는게 좋아보입니다!

2022-03-29 09:14 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +    def modal(self, context, event):
앗..! 단일 파일만 저장할 때는 `basename` 이랑 현재 `scene.name` (= `qitem.name`)이랑 다를 때 이름 업데이트하고 저장할 때 파일 확장자 붙여주는 동작이 미세하게 달라서 `Acon3dRenderOperator` 에 본래의 `modal` 이 들어가고 `Acon3dRenderFileOperator` 는 오버라이드라고 생각하시면 될것 같습니다!
`Acon3dRenderDirOperator` 는 `Acon3dRenderOperatro` 의 `modal` 만 받아와서 써도 되기 때문에 비워져 있습니다.

2022-03-29 09:16 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +            self.filepath = "untitled"
같은 방법으로 Save, Save As 에서 빈 파일 저장할 때 `untitled` 를 넣어주고 중복되는 파일이 있으면 숫자 추가하는 방법을 쓰면 되겠다고 생각했습니다.
그건 다음에 한번 얘기 해보겠습니다.

2022-03-29 09:17 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +class Acon3dRenderQuickOperator(Acon3dRenderFileOperator):
감사합니다!

2022-03-29 09:19 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +    def modal(self, context, event):
`Acon3dRenderDirOperator` 는 `Acon3dRenderOperator` 의 `modal` 사용
`Acon3dRenderFileOperator`는 `Acon3dRenderOperator` 의 `modal` 을 오버라이딩 해서 사용
입니다!

2022-03-29 09:24 UTC, Youdiie commented on release/scripts/startup/abler/render_control.py
> +    def modal(self, context, event):
아 제가 코멘트 위치를 잘못 잡았네요. 제가 말씀드린건 `Acon3dRenderOperator`를 추상클래스로 두고 실제 구현하는 modal 내용을 `Acon3dRenderDirOperator`, `Acon3dRenderFileOperator`에서 각각 구현하자 습니다!

2022-03-29 11:29 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +    def modal(self, context, event):
수정 완료했습니다!

2022-03-30 01:33 UTC, Youdiie commented
바꾼 코드 구조로 기능은 잘 작동하네요! 현 기능에 대해서 저는 어프룹임니다 :)

+ 보완할 사안은 요 브랜치 위에서 작업하실 건가요 혹은 기록용인가요?
하나 추가했으면 하는게 폴더 저장시엔(All Scene, Snip Render) 폴더로 저장됨을 유저가 알 수 있게 하면 좋겠슴니다!

2022-03-30 01:33 UTC, Youdiie approved these changes

2022-03-30 01:36 UTC, seungha-kim requested changes
앗 이제 확인했는데, 저는 수정 요청드립니다!

클래스의 순서가 많이 바뀌었는데, 이렇게 반드시 필요하지 않은 이유(UI의 패널 순서와 클래스 정의 순서가 일치했으면 좋겠다)로 코드가 많이 수정되는 것은 좋지 않습니다!

- 코드에 의미없는 diff가 많아지게 됩니다 -> 코드리뷰 할 때도 좋지 않고, 나중에 히스토리를 살펴볼 때도 좋지 않습니다
- UI 구성은 기획에 의해 언제든 바뀔 수 있습니다 -> UI가 바뀔 때마다 코드 순서를 바꾸는 것은 어렵습니다

클래스 순서를 원래대로 돌려주시기를 요청 드립니다!

2022-03-30 03:22 UTC, habijung commented
@Youdiie
보완할 사항은 기록용입니다! 추후 기능 추가 예정이면 추가 브랜치를 파서 작업하는게 좋을 것 같습니다. 피드백 추가했습니다!

@seungha-kim 
diff 문제는 고민했었는데, 기획에 따라 UI 구성이 언제든 달라지는건 미처 생각하지 못했네요. 피드백 감사드리고 해당 부분 반영해서 수정했습니다!

2022-03-30 04:23 UTC, seungha-kim commented
감솨합니당!!! 커밋 정리만 조금 하면 좋을 것 같은데, 요건 허들 가시죵

2022-03-30 06:40 UTC, seungha-kim approved these changes
저는 어프룹 눌러놓겠슴다!! @sdkfile 이어서 리뷰 해주시죵

2022-03-30 08:27 UTC, sdkfile requested changes
이정도 제외하고는 문제 없습니다!!!

2022-03-30 08:27 UTC, sdkfile commented on release/scripts/startup/abler/render_control.py
> +                self.basename = ".".join(self.basename.split(".")[0:-1])
이것도 마찬가지

2022-03-30 08:36 UTC, habijung commented on release/scripts/startup/abler/render_control.py
> +            self.basename = ".".join(self.basename.split(".")[0:-1])
처음에 split 이것저것 해본다고 앞에 붙였었는데 정리를 못했네요. 다음에 더 깔끔하게 정리하겠습니다!

2022-03-31 09:20 UTC, sdkfile approved these changes

2022-03-31 09:20 UTC, merged