[0.2.4 QA] UI Number Input에 원하지 않는 인풋이 입력되었을 경우를 필터링함
ACON3D/blender pull request #102
Opened 2022-08-02 04:54 UTC by sdkfile

## 이슈 내용

### 재현 환경

- 윈도우11
- 0.2.4

### 재현 경로

- Image Adjustment > Brightness / Contrast
    - Contrast 에 -001 입력

### 현재 상태

- 오류 발생

  ![image](https://user-images.githubusercontent.com/43770096/182294088-5b2fbfa6-8473-4d8d-bcd6-4629019e3fec.png)

- -1 입력시에는 오류 발생하지 않음.
- 문제 발생 가능 필드
    - Image Adjustment > Brightness / Contrast
        - Brightness
        - Contrast
    - Shadow / Light Control > Shadow
        - Altitude
        - Azimuth
    - Camera Control > Background Images
        - Offset X
        - Offset Y
        - Rotation

## 코드 수정 내용
아래의 적정상태에 맞도록 개선하였습니다.
### 적정 상태

1. `-` 문자가 n개 들어가는 경우 : `-`를 하나만 붙이고 leading zeros도 걸러진 숫자와 합쳐서 python으로 전달
2. string literal이 입력 되었을 때의 경우 (`-`, `+`, `.`제외) : 아무 행동도 하지 않도록 반환

2022-08-02 05:04 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +    if (!isdigit(str[i]) && str[i] != '.' && str[i] != '-' && str[i] != '+') {
str[i] 가 중복해서 쓰이니 위에서 변수를 만들고 쓰는 것은 어떨까요?

2022-08-02 05:07 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +    str++;
위 if 문을 없애고, while 문에 isNegative 를 같이 쓰는 것은 어떨까요?

2022-08-02 05:12 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +  }
- 가 나오지 않을 때까지 일괄적으로 없인뒤, 0 를 일괄적으로 없애는 것으로 보이는데,
-0-0-001 과 같은 경우에는 - 가 다 걸러지지 않아서 계속 에러가 발생할 것 같습니다

2022-08-02 05:39 UTC, JJong84 requested changes

2022-08-02 05:39 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +  }
-가 나오지 않을 때까지 일괄적으로 -를 없앤 뒤, 0 도 똑같이 처리하는 것으로 보이는데,
-0-0-001 과 같은 경우에는 - 가 다 걸러지지 않아서 계속 에러가 발생할 것 같습니다

2022-08-02 06:51 UTC, sdkfile commented on source/blender/editors/interface/interface.c
> +    if (!isdigit(str[i]) && str[i] != '.' && str[i] != '-' && str[i] != '+') {
메모리를 더 쓸 것인가, 액세스 수를 줄일 것이냐에 대한 내용인것 같은데, 메모리가 맞는 것 같군요 오케이

2022-08-02 08:05 UTC, sdkfile commented on source/blender/editors/interface/interface.c
> +  }
해당 부분 처리 가능하도록 `-`가 처음에만 들어가는 케이스를 제외하고는 다 string 처리하도록 하였고, `-`에 관련된 while 문을 if 문으로 변경하였습니다.

2022-08-02 08:06 UTC, sdkfile commented on source/blender/editors/interface/interface.c
> +    str++;
적용하였습니다

2022-08-02 08:06 UTC, sdkfile commented on source/blender/editors/interface/interface.c
> +    if (!isdigit(str[i]) && str[i] != '.' && str[i] != '-' && str[i] != '+') {
변수 만들어서 적용했습니다~!

2022-08-02 08:06 UTC, sdkfile commented
@JJong84 리뷰해주신 내용 적용하여 커밋 하였습니다 :)

2022-08-02 08:10 UTC, seungha-kim commented
@sdkfile `001` 때문에 저번에 한 번 수정하셨었는데, 그게 `-001` 을 못 걸러줘서 추가 수정하신 거 맞을까요?

2022-08-02 08:13 UTC, JJong84 requested changes

2022-08-02 08:13 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +    if ((!isdigit(digit) && digit != '.' && digit != '-' && digit != '+') || (i > 0 && digit == '-')) {
i > 0 일 때 '+' 인지도 체크가 필요해보입니다..!
이 부분을 통해서 while 문 하나를 줄일 수 있어서 좋은 것 같습니다!

2022-08-02 08:13 UTC, JJong84 commented on source/blender/editors/interface/interface.c
> +  // added while loop to strip leading '-' characters in str
위에서 -- 인 경우를 모두 거르게 변경하셔서 주석 두개 다 수정하면 좋을 것 같습니다!

2022-08-02 08:23 UTC, seungha-kim commented
[질문] 최초에 leading zero 를 제거하는 작업이 어떤 목적으로 이루어졌는지 제가 맥락 파악을 못하고 있어서 드리는 질문입니다 -

일단 Blender 에서 이미 적절치 않은 문자열이 number field 에 들어왔을 때, 입력이 되지 않고 더해서 사용자에게 적절한 피드백도 가고 있는것으로 보이는데요!

<img width="749" alt="image" src="https://user-images.githubusercontent.com/767106/182327076-082ac38f-dee1-4290-9f21-5aed8a995e2e.png">
<img width="548" alt="image" src="https://user-images.githubusercontent.com/767106/182327103-68079807-dabb-447a-ba12-9f9806edf63c.png">

위에서 나는 것처럼 에러가 났을 때 사용자가 "내가 잘못 입력해서 생긴 에러인가봐" 라고 인식할 수 있다면 크게 문제가 있는 UI는 아니라고 느껴져요. 그래서 우리가 모든 경우의 수를 다 처리해야 할 이유도 없어보입니다.

다만 이전에 leading zero 제거 처리를 했던 것은 "이건 블렌더가 에러라고 처리하는 것이 이상하다. 0이 앞에 붙어있는 숫자는 우리 사용자들이 문제없이 쓸 수 있어야 한다" 는 합의가 있었기 때문에 기존 작업내용대로 처리가 됐었던 것으로 보이는데용

그러면 "-001도 우리가 처리를 해주어야 하는가?" 혹은 "우리는 어디까지 처리를 해주어야 하는가?" 는 질문을 해봐야할 것 같아요. 저는 "-001은 처리를 안 해주어도 될 것 같다"는 생각입니다!

2022-08-02 08:27 UTC, seungha-kim commented
만약 `-001` 까지 편하게 쓸 수 있게 처리해주자! 라고 결정이 된다면, "`-001` 에 대해서는 우리가 편하게 쓸 수 있게 처리해준다. 나머지는 에러가 나도 어쩔 수 없다." 는 쪽으로 가도 괜찮지 않을까 합니다. `--003`, `-0-0-001` 같은 엣지 케이스는 그냥 에러가 나도 괜찮을 것 같다는 생각이에요.

또 만약 `--003`, `-0-0-001` 같은 요상한 leading zero 케이스도 처리해주자! 라고 결정이 난다면 (ㅠㅠ) "0이 아닌 digit 이 나올때까지 0만 뺀다, 나머지는 기존 처리방식대로 처리한다" 와 같은, leading zero 제거만 신경쓰는 알고리즘을 쓰면 어떨까 합니다.

2022-08-02 08:58 UTC, seungha-kim commented on source/blender/editors/interface/interface.c
> +    str = str_new;
`str = str_new` 에서 둘 중 하나는 memory leak 이 될 가능성이 높아 보입니다.

2022-08-02 09:53 UTC, seungha-kim commented
개선했다고 생각했으나 문제가 있는 알고리즘 링크 달아놓습니다. https://replit.com/@seungha/takeoffleadingzero#main.py

2022-08-02 09:54 UTC, seungha-kim commented
논의 결과 간단정리: 여러 엣지케이스들을 고려한 알고리즘을 짜기가 쉽지 않을 것 같으므로, `-001` 은 (하게 된다면) 다음 릴리즈에 넣어야 할 것 같다. `001` 을 0.2.4에서 빼는 것도 고려해보자.

2022-08-03 08:18 UTC, sdkfile commented
@seungha-kim @JJong84 
- 논의 내용
leading zero 문제를 `+` , `-` 등 다양한 케이스에 대해서 처리하기에는 로직적으로 문제가 너무 많을 것 같다.
차라리 001 과 같은 입력 케이스도 -001 과 같은 케이스와 동일한 경험으로 오류로 사용자가 인지하도록 하는게 좀 더 맞는 방향일 것 같음
- Decision
001 입력시 오류가 발생했던 것에 대한 작업 사항을 롤백한다.

이런 결정을 하여 해당 PR 닫고, 이슈에서는 롤백 PR을 참조하도록 하겠습니다

2022-08-03 08:18 UTC, closed without merging