password를 입력했을 때 해당 내용이 그대로 undo history에 노출 되는 현상
ACON3D/blender pull request #116
Opened 2022-08-10 10:09 UTC by sdkfile

UI 업데이트 시에 rnaProperty의 identifier가 password, password_shown, username 이면 undo stack에 쌓이지 않도록 수정

2022-08-10 10:10 UTC, JJong84 requested changes

2022-08-10 10:10 UTC, JJong84 commented on source/blender/editors/interface/interface_handlers.c
> +    if (strcmp(rna_id, "password") || strcmp(rna_id, "password_shown") || strcmp(rna_id, "username")){
아까 말씀하셨던 것처럼 리스트로 제외할 프로퍼티 빼면 좋을 것 같습니다!

2022-08-10 10:25 UTC, sdkfile commented on source/blender/editors/interface/interface_handlers.c
> +    if (strcmp(rna_id, "password") || strcmp(rna_id, "password_shown") || strcmp(rna_id, "username")){
@JJong84 완료했습니다

2022-08-11 01:00 UTC, JJong84 approved these changes
오랜만에 c 코드 보려니까 쉽지 않네요.. 어프룹 드리겠습니다!
고생하셨습니다!

2022-08-11 02:44 UTC, merged