import시 File dialog에서 빈 곳을 클릭하면 뜨는 버그를 resolve
ACON3D/blender pull request #119
Opened 2022-08-16 09:29 UTC by sdkfile

## 발제/내용

### **어떤 현상이 발생하고 있었나요? 가능하다면 스크린샷/영상을 첨부해주세요.**

- 빈 문자열을 받아 파일 열기를 했을 때 에러 발생

### **어떤 경로를 통해서 인지하게 되었나요? 내부인원 이용, CS인입 등**

- 센트리 오류
    
    [[Sign In | Sentry](https://sentry.io/organizations/carpenstreet/issues/2785438622/?environment=production&project=6046815&query=is%3Aunresolved)](https://sentry.io/organizations/carpenstreet/issues/2785438622/?environment=production&project=6046815&query=is%3Aunresolved)
    

### **해당 오류의 이해관계자는 어디까지인가요? (해당 인원에게 안내를 목적으로 합니다)**

- 알앤디 개발셀

## 대응

### **재현 방법이 어떻게 되나요?**

- 파일 창 열었을 때 빈 곳을 더블 클릭하면 발생

### 그래서 이 현상은 1)언제부터 2)어디에서 3)어떤 이유로 생겼나요?

- 빈 문자열일 때 suppress하는 코드가 없어서 발생
- 동일한 현상이 [Import FBX]에도 발생하므로 같이 달아주면 될거 같습니다.

[https://acontainer.slack.com/archives/C02K1NPTV42/p1657785061394089](https://acontainer.slack.com/archives/C02K1NPTV42/p1657785061394089)

### 어떤 조치를 취했나요?

- [x]  이전에 스듴님이 [File Open] 버튼에 넣은 코드가 있어서 [Import], [Import FBX] 에도 달아주면 됨
    
    [https://github.com/ACON3D/blender/pull/57](https://github.com/ACON3D/blender/pull/57)
    
- [x] ImportHelper를 오버라이딩하는 AconImportHelper 클래스를 만들어서 ImportHelper를 사용하는 Import, File Open, Import FBX에 모두 적용함.

2022-08-16 09:34 UTC, Youdiie commented on release/scripts/startup/abler/general.py
>              tracker.file_open()
안바뀐 부분은 코멘트가 안달아지네요🥲
269-270줄 내용이 AconImportHelper에 있으니 해당 줄 삭제해도 될거 같습니다!

2022-08-16 09:47 UTC, sdkfile commented on release/scripts/startup/abler/general.py
>              tracker.file_open()
아까 지우고 푸시 하려고 했는데 까먹었었네용 고쳤습니다!! @Youdiie

2022-08-16 10:26 UTC, Youdiie approved these changes
고생하셨습미다~

2022-08-16 23:49 UTC, JJong84 requested changes

2022-08-16 23:49 UTC, JJong84 commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
AconImportHelper 의 execute 는 Return 값이 {"FINISHED"} or None 인데,
실제로 위 함수를 사용하고 있는 다른 클래스에서는 None 인지 체크만 하고 있습니다.
현 함수의 return 을 boolean 으로 변경하거나, 현 함수를 사용하는 부분에서 현 함수를 Return 값을 사용하도록 변경하는 것은 어떨까요?

2022-08-17 00:49 UTC, sdkfile commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
기존의 execute 함수를 overiding 해서 쓰기 때문에 컨벤션에 맞게 Optional로 {"FINISHED"}를 반환하도록 하였습니다.

수정을 필요로 하지는 않는 것 같아요! @JJong84

2022-08-17 00:57 UTC, JJong84 commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
넵! 그리고 방금 떠오른 것인데,
실제 사용하는 부분의 execute 는 `bpy.types.Operator `의 execute 를 상속받아 오버라이딩해서 사용하고 있는 것이고,
위 `ImportHelper` 의 execute 함수는 path 체크만 해서 넘겨주는 역할을 하고 있고 실제 사용하는 부분에서 오버라이딩을 해서 쓰고 있지는 않아서 약간 혼동의 여지가 있을 것 같습니다.
context Argument 를 지우고, 함수 이름을 변경하는 것은 어떨까요?

2022-08-17 01:35 UTC, sdkfile commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
이건 좋은 선택지인것 같아요. @JJong84 

`def check_path(self):`와 같이 만들고 자식 클래스에서는 `AconImporterHelper.check_path()`를 사용하자는 말씀이시죠? 그러면 boolean으로 반환 해도 될 것 같습니다.

2022-08-17 01:36 UTC, JJong84 commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
네네 맞습니다! :)

2022-08-17 08:33 UTC, sdkfile commented on release/scripts/startup/abler/lib/import_file.py
> +            return {"FINISHED"}
반영했습니다 @JJong84

2022-08-17 08:42 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +            if not AconImportHelper.check_path(self):
이제 상속으로 인해 이름이 중복되는 일이 없어서,
self.check_path 로 수정해도 좋을 것 같습니다!

2022-08-17 08:50 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +            if not AconImportHelper.check_path(self):
수정 완료

2022-08-17 09:09 UTC, JJong84 approved these changes
고생하셨습니다!

2022-08-18 04:52 UTC, merged