더블클릭으로 에이블러 실행 시, 업데이트가 있으면 알려주기
ACON3D/blender pull request #130
Opened 2022-08-23 09:53 UTC by habijung

## 관련 링크

- Notion: [더블클릭으로 에이블러를 열었을 때, 업데이트가 있으면 알려주기](https://www.notion.so/acon3d/3c7bdc2650654794ad841c8937a6da37)

## 발제

- 에이블러를 더블클릭으로 열었을 시, 새로운 업데이트가 있음을 알린다.
- 최대한 사용자들이 에이블러 버전을 한가지만 사용할 수 있도록 유도한다.

## 대응

### 어떤 조치를 취했나요?

**STEP 01.**
에이블러 클라이언트 실행 시, 로컬 프로그램 버전과 서버 프로그램 버전을 확인
- 로컬 프로그램과 서버 프로그램의 버전 확인을 위해서 `lib/version.py` 추가

**STEP 01. > CASE 01.**
더블 클릭으로 에이블러를 실행하고, 로컬 버전 >= 서버 버전일 때, 업데이트 팝업 없이 에이블러 계속 실행

**STEP 01. > CASE 02.**
더블 클릭으로 에이블러를 실행하고, 로컬 버전 < 서버 버전일 때, 에이블러 실행 시 팝업 노출
- 팝업 관련 함수는 `operator.py` 에 정의함

**STEP 01. > CASE 02. > Update ABLER 클릭 시**
에이블러를 종료하고, 자동으로 AblerLauncher 를 실행
- 에이블러 종료는 가능하나, 현재 관리자 권한 문제로 `subprocess` 를 실행할 수 없음
- `subprocess.call(프로그램, shell=True)` 옵션으로 관리자 권한 프로그램 실행
- 관리자 권한 프로그램 (런처) 이 실행되면서 에이블러 종료가 되지 않는 문제가 있음. 그렇지만, 런처로 에이블러 업데이트 후 실행하면, 기존의 에이블러는 종료되고 업데이트 된 에이블러가 실행됨.

**STEP 01. > CASE 02. > OK 클릭 시**
팝업을 닫고, 에이블러 클라이언트를 사용 가능한 상태로 만든다.

**STEP 02.**
업데이트 끝나고 에이블러 실행

**STEP 03.**
업데이트 된 (혹은 되지 않은) 에이블러 정상 사용

## 결과

![image](https://user-images.githubusercontent.com/52474700/186128912-9456c49e-357a-4bc8-9deb-218135287fd0.png)

2022-08-23 09:54 UTC, habijung commented
번역 PR 머지 후 해당 PR을 머지할 예정입니다.

2022-08-24 01:03 UTC, sdkfile commented
이거 저도 리뷰할게요 @habijung

2022-08-24 01:07 UTC, Youdiie commented on release/scripts/startup/abler/lib/version.py
> +        bpy.ops.acon3d.update_alert(
여기 아래는 다른 함수로 묶는게 좋을거 같습니다! show_upadate_message() 같은걸루용

2022-08-24 01:07 UTC, Youdiie commented on release/scripts/startup/abler/operators.py
> +class Acon3dUpdateAlertOperator(bpy.types.Operator):
요 클래스를 재활용하려고 title, message_1, message_2를 받게끔 하신거라면 bl_idname을 `acon3d.show_alert` 같이 범용적인 단어로 쓰는게 좋을거 같아요!
재활용이 아닌 업데이트를 위한 alert로 쓴다면 굳이 title, message_1, message_2를 받지않고 
```
title="Latest version found for ABLER. Do you want to update?",
message_1="When using an older version of ABLER, some features may not work properly.",
message_2="If you click the OK button, you can close the pop-up and use ABLER with the current version.",
```
요 내용을 직접 넣어주는게 코드 가독성 면에서 좋은거 같습니다.

2022-08-24 01:07 UTC, Youdiie commented on release/scripts/startup/abler/operators.py
> +        bpy.ops.wm.quit_blender()
블렌더를 먼저 끄고 subprocess.call 이 실행되군요! 신기합니다

2022-08-24 01:07 UTC, Youdiie commented on release/scripts/startup/abler/operators.py
> +from .lib.version import get_config, compare_version
compare_version은 여기서 안쓰이니 삭제해주세요~

2022-08-24 07:28 UTC, sdkfile requested changes
수정사항 적어서 드립니다! @habijung

2022-08-24 07:28 UTC, sdkfile commented on release/scripts/startup/abler/lib/version.py
> +def get_config():
이 함수 이름이 get_config인데, launcher의 path도 같이 반환하는건 모양이 이상해보여요. 함수 분리하는게 어떨까요?

2022-08-24 07:28 UTC, sdkfile commented on release/scripts/startup/abler/lib/version.py
> +    launcher, config = get_config()
여기서만 개선점을 얘기하자면 `_, config = get_config()`가 될 것 같습니다. 아래에서 launcher이라는 변수는 사용되지 않으니까요.

2022-08-24 07:28 UTC, sdkfile commented on release/scripts/startup/abler/lib/version.py
> +    with open(config, "r") as f:
이렇게 하는 방법도 있을텐데, 
[configparser](https://docs.python.org/ko/3/library/configparser.html)를 써서 유려하게 정보를 받아올 수 있을 것 같아요

2022-08-24 07:28 UTC, sdkfile commented on release/scripts/startup/abler/lib/version.py
> +    finally:
제가 생각하기에는 만약 req가 이상하게 반환되었다면 아래에 있는 for 문 돌릴때, `req["assets"]`가 존재하지 않아서 또 에러가 날 수도 있다고 생각합니다.
앞에 `if "assets" in req.keys()` 조건을 달아주는 것이 좋을 것 같습니다.

2022-08-24 07:28 UTC, sdkfile commented on release/scripts/startup/abler/operators.py
> +        subprocess.call(launcher, shell=True)
이렇게 하면 shell 창이 뜨던가요? 아마 아닌걸로 알고 있긴 한데 혹시 몰라서 여쭤봅니다!

2022-08-24 07:53 UTC, Youdiie commented on release/scripts/startup/abler/lib/version.py
> +    with open(config, "r") as f:
유려하게~

2022-08-24 07:56 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    # 에이블러 버전만 비교하기
처음 개발 시에 런처 버전까지 확인하고 비교하는걸로 이해해서 들어갔는데, 이해하기 쉽도록 abler_ver 만 남겨두도록 하겠습니다.

2022-08-24 07:59 UTC, habijung commented on release/scripts/startup/abler/operators.py
> +class Acon3dUpdateAlertOperator(bpy.types.Operator):
재활용이 아닌 에이블러 업데이트 팝업에만 사용하려고 만든 의도였기 때문에, 후자의 방법으로 수정하겠습니다!

2022-08-24 08:04 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +        bpy.ops.acon3d.update_alert(
아래 코멘트에서 팝업 오퍼레이터 내용을 수정하게 되면, `bpy.ops.acon3d.update_alert()` 부분이 간략하게 줄일 수 있을 것 같고, 이 함수명 `compare_version()` 을 수정하는 것이 더 좋을 것 같습니다.

2022-08-24 08:08 UTC, habijung commented on release/scripts/startup/abler/operators.py
> +        bpy.ops.wm.quit_blender()
기획 시나리오 순서로 코드를 넣기는 했는데, 코드가 실행되길래 저도 신기하긴 했습니다.
그래도 문제가 있다면, `bpy.ops.wm.quit_blender()` 가 실행되어도 관리자 권한 요구 프로세스 때문에 바로 종료되지 않습니다.
그래도 런처 동작이 전부 끝나고 Run ABLER 를 하면 정상적으로 종료되어서 그렇게 진행했습니다.

2022-08-24 08:08 UTC, habijung commented on release/scripts/startup/abler/operators.py
> +from .lib.version import get_config, compare_version
앗! 확인 감사합니다~

2022-08-24 08:17 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +        bpy.ops.acon3d.update_alert(
해당 함수명을 `show_update_alert()` 로 수정했습니다.

2022-08-25 00:15 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +def get_config():
넵! 따로 분리하도록 하겠습니다.

2022-08-25 00:17 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    launcher, config = get_config()
피드백 감사합니다! 어떻게 처리할까? 했는데 앞으로 `_` 를 더 잘 써먹겠습니다.
`get_config()` 함수 수정하면서 필요한 부분 반영하겠습니다.

2022-08-25 01:01 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    with open(config, "r") as f:
configparser 활용해서 더욱 유려하게 수정했습니다!

2022-08-25 01:02 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    # 에이블러 버전만 비교하기
launcher_ver은 필요 시에 추가하면 될 것 같으니, 지우고 abler_ver만 남겼습니다.

2022-08-25 02:30 UTC, habijung commented on release/scripts/startup/abler/operators.py
> +        subprocess.call(launcher, shell=True)
따로 shell 창이 뜨지는 않습니다!
기존 프로그램 동작과 동일하게 프로그램 오픈 시에만 잠깐 나왔다가 에이블러가 실행되면 사라집니다.

2022-08-25 02:36 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    finally:
오, 이 부분을 어떻게 처리할지 고민하고 있었는데 request 정보를 key 값으로 찾을 수 있군요. 피드백 감사합니다. 바로 반영하겠습니다.

2022-08-25 05:21 UTC, sdkfile commented on release/scripts/startup/abler/lib/version.py
> +    finally:
이부분까지 처리되면 말씀해주세요! @habijung

2022-08-25 05:24 UTC, habijung commented on release/scripts/startup/abler/lib/version.py
> +    finally:
앗! 제가 resolve 처리를 안했었나요? 코멘트 달 때 바로 반영하고 push 했습니다!

2022-08-25 05:33 UTC, sdkfile approved these changes
오케이 확인했습니다 고생하셨습니다 👍

2022-08-25 05:40 UTC, Youdiie approved these changes
고생하셨습니다!
추가로 하나 남겼는데 하비님께서 보시고 굳이 싶으시면 넘어가도 좋습니다~

2022-08-25 05:40 UTC, Youdiie commented on release/scripts/startup/abler/operators.py
> +        row.label(text=self.title)
요건 선택사항인데 title, message_1, message_2을 직접 여기다가 넣어주면 코드가 약간 줄지않을까 싶습니다ㅎㅎ

2022-08-25 05:59 UTC, habijung commented on release/scripts/startup/abler/operators.py
> +        row.label(text=self.title)
요거는 앞으로 내용 바뀔 일이 거의 없겠지만, 그래도 한곳에 변수로 모아두는게 나중에 메세지 관리하기 더 편하지 않을까 싶습니다!

2022-08-25 08:40 UTC, merged