아웃라이너에서 카메라를 지워서 없을 때, 새로운 카메라를 만들어서 카메라뷰로 켜주는 로직 추가
ACON3D/blender pull request #135
Opened 2022-09-06 07:30 UTC by sdkfile

## 관련 링크
[노션 링크](https://www.notion.so/acon3d/Nonetype-a25d1c51174d4b11a9597f9f041b3ce4)

## 발제/내용

- 아웃라이너에서 View Camera를 지우고 씬을 추가하는 경우에 old_scene의 씬 카메라 정보가 없어서 Nonetype 에러가 나고 있었음
![image](https://user-images.githubusercontent.com/43770096/188572858-e5f4be21-10de-44ed-aefd-77dc57beaee5.png)

## 대응

### 어떤 조치를 취했나요?

- [x]  old_scene의 카메라 정보가 없을 경우, 새로 카메라를 추가함
- [x]  해당 카메라를 scene에 추가함
- [x]  그 카메라를 중심으로 camera view를 켜줌

2022-09-06 07:36 UTC, JJong84 reviewed
전반적으로 함수 아래있는 공백들이 사라졌는데, 의도된 것인가요?

2022-09-06 07:36 UTC, JJong84 commented on release/scripts/startup/abler/lib/scenes.py
> +        cam2 = bpy.data.cameras.new("View Camera")
cam, obj 라는 변수를 쓰고있지는 않으니까 2를 없애도 괜찮지 않을까요?

2022-09-06 07:42 UTC, sdkfile commented on release/scripts/startup/abler/lib/scenes.py
> +        cam2 = bpy.data.cameras.new("View Camera")
아 맞네요 이거 obj를 scene에 등록하기 전에 사용했더니 세그폴트가 나서 저렇게 놓고 했었어요. 다시 수정해놓을게요

2022-09-06 07:45 UTC, sdkfile commented on release/scripts/startup/abler/lib/scenes.py
> +        cam2 = bpy.data.cameras.new("View Camera")
위에 공백들 포함하여 수정사항 모두 반영하였습니다!

2022-09-06 07:46 UTC, JJong84 approved these changes
고생하셨습니다!
(공백같은 경우에는 추후 다른 브랜치에서 지워지면 좋을 것 같습니다..!)

2022-09-07 01:57 UTC, habijung requested changes
카메라 뷰를 활성화 시켜줄 때, 지금 `passepartout`가 활성화 되고 있는 것으로 보입니다.
이 부분이 `turn_on_camera_view`에서 처리가 되어야 하는 것으로 알고 있는데, 적용이 되지 않는 이유를 모르겠습니다.
혹시 `bpy.context.scene.camera.data.show_passepartout = False` 로 직접 비활성화 해주면 해당 옵션이 비활성화가 될까요?

2022-09-07 08:23 UTC, sdkfile commented
> 카메라 뷰를 활성화 시켜줄 때, 지금 `passepartout`가 활성화 되고 있는 것으로 보입니다. 이 부분이 `turn_on_camera_view`에서 처리가 되어야 하는 것으로 알고 있는데, 적용이 되지 않는 이유를 모르겠습니다. 혹시 `bpy.context.scene.camera.data.show_passepartout = False` 로 직접 비활성화 해주면 해당 옵션이 비활성화가 될까요?

@habijung 이 내용 더 설명이 필요할 것 같습니다!

2022-09-13 08:22 UTC, sdkfile commented
> > @habijung 이 내용 더 설명이 필요할 것 같습니다!
> 
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/52474700/189013032-6c21ec60-a1f3-4fd7-af2d-7944af68e3b3.png">
> 
> 에이블러에서는 기본적으로 활성화된 카메라 바깥쪽 영역 `passepartout`을 꺼주고 있으니, false 하는 옵션이 추가되어야 하는 것으로 보입니다!

반영 완료했습니다~!! 확인 부탁드릴게요 ㅎㅎ

2022-09-13 09:50 UTC, habijung approved these changes
문제 없이 정상적으로 Passepartout 꺼지는 것을 확인해서 어프룹입니다!

2022-09-14 00:46 UTC, merged