파일 오픈 후, .blend 파일 import 에러 처리
ACON3D/blender pull request #138
Opened 2022-09-15 04:42 UTC by habijung

## 관련 링크

- [[Import] 파일 오픈 후, 다른 파일 Import 하면 Layer0.001 레이어가 생기는 문제](https://www.notion.so/acon3d/Import-Import-Layer0-001-aa80454dc11c4321bfdad23d6b617227)
- [[Import] 파일 오픈 후, 같은 파일 Import 하면 Layer 오류 발생](https://www.notion.so/acon3d/Import-Import-Layer-cb39914724cc410e9a5e83d50a0a0055)

## 발제/내용

- 에이블러에서 `.blend` 파일을 오픈하고, 다른 파일을 import 하면 중복 레이어 (이름이 같은) 에 대해서 `.001` 과 같은 Blender 넘버링이 추가되고, 노출하지 않는 `Layer0.xxx` 이 레이어 패널에 노출됩니다. 그래서, 레이어 중복 처리를 해주었습니다.
- 에이블러에서 `.blend` 파일을 오픈하고, 경로와 이름이 같은 (`filepath`가 같은) 파일을 import 하면 중복 레이어와 오브젝트에 대해서 에러가 발생하고 있었습니다. 그래서, 같은 파일에 대해서는 에러 알림을 노출하는 것으로 수정하였습니다.

## 대응

### 어떤 조치를 취했나요?

분량이 많아서 Notion 문서로 확인하는 것이 좋습니다.

### 파일 오픈 후, 다른 파일 import

- Import 실행하고 `Layers` 콜렉션을 탐색할 때, child 레이어의 이름에 Layer0 문자열이 포함되어 있으면 별도 처리를 함
- `Outliner` > `Blender File` 에는 있는 Meshes 혹은 Objects 데이터가 View Layer 에 없는 상태에서 View Layer의 기능을 수행할 때 `RuntimeError` 에러가 나타남. 그래서 별도 처리를 함

### 파일 오픈 후, 같은 파일 import

- 현재 열려 있는 파일의 `filepath` 와 import 에 사용되는 `filepath`를 비교함
- 현재 열려 있는 파일이 New > General 이면 filepath가 없을 수 있음
- 만약, filepath가 없거나, 열린 filepath와 import filepath가 같다면 → 같은 파일 import 처리 `alert`를 띄우고 import 종료
- 기획된 에러 메세지 반영

### 번역 작업 Merge 되면 해당 PR Merge 할 예정입니다.

2022-09-15 09:06 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
에러 메세지는 아래에서 관리하고 있으니 raise SameImportException? 요렇게 하고 밑에서 분리하는게 어떨까용

2022-09-15 09:06 UTC, Youdiie commented on release/scripts/startup/abler/general.py
>              for obj in data_to.objects:
아니면 212줄을 없애는게 어떨까요? import한 블렌더 파일의 select까지 살릴필요는 없을거 같아요

2022-09-15 09:07 UTC, Youdiie commented on release/scripts/startup/abler/general.py
>              for obj in data_to.objects:
요거 두번째 코멘트에 이은 코멘트입니닷

2022-09-16 01:17 UTC, habijung commented on release/scripts/startup/abler/general.py
> +                        # File Open과 다른 파일을 import 할 때, Layer와 Object 이름이 중복되면 ".001"부터 넘버링됨
여기서 Layer, Object는 Scene Collection의 하위 Layers와 그 child collection이 아닌, 에이블러에서 레이어라고 정의하고 있는 `Collection` 과 `Mesh` Object 를 말하고 있었습니다.
헷갈리지 않도록 설명 보충하겠습니다.

2022-09-16 01:17 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
적용해보겠습니다!

2022-09-16 01:47 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
커스텀 `Exception`을 만드려면 Class 상속이 필요해서, `ImportError` 라는 bool 값으로 관리하면서 `raise` 발생으로 exception에서 같이 관리할 수 있도록 적용했습니다.

2022-09-16 01:56 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
ImportError는 너무 포괄적인 이름 같아요! 같은 이름에서 발생한 Error임을 명시할 `SameFileError` 요런식으로 하는게 어떨까요?

2022-09-16 01:56 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
+ Class로 관리하는게 좋을거 같아요! bool로 관리하면 다른 에러가 생길때마다 또 변수를 추가하는 번거로움이 생깁니다. 또 `raise OOError `요런식으로 하는게 일반적이기도 하고요
`credential_modal.py`에서 종류별로 에러 관리하는 방식 비슷하게 쓰면 될거 같아요.

2022-09-16 07:30 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            if filepath_curr == filepath:
Import 내부에서 일어나는 오류이기 때문에 Import Operator 내부의 중첩 클래스로 구현하고, `except` 구분을 해주었습니다.

2022-09-16 07:35 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            # View Layer에 포함된 오브젝트 가져오기
> 아니면 212줄을 없애는게 어떨까요? import한 블렌더 파일의 select까지 살릴필요는 없을거 같아요

코멘트까지 포함해서, 짧은 논의 후 View Layer에 보이지 않는 Mesh Object들은 `select_set(True)`를 하지 않는 것으로 수정했습니다.
추가로, `.blend` 파일 import에 사용하는 방법이 `bpy.data.libraries.load(filepath)`인데, 여기서 오브젝트가 View Layer에 있는지 없는지 전부 확인하는 것은 조사 후 힘든 것으로 판단했습니다.

2022-09-16 07:36 UTC, habijung commented on release/scripts/startup/abler/general.py
>              for obj in data_to.objects:
> 요 작업이 import 속도에 저하를 주는거 같습니다. 차라리 View Layer에 없는 오브젝트는 처음부터 import 안하면 어떨까요?

에서 같이 처리하였습니다.

2022-09-16 07:48 UTC, Youdiie approved these changes
어프룹입니닷!

2022-09-16 08:16 UTC, sdkfile requested changes

2022-09-16 08:16 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> -
불필요한 변경사항은 빼주세요

2022-09-16 08:16 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> -            FILEPATH = self.filepath
이부분을 위로 울리고 공백 등 불필요한 변경사항을 뺄 수 있으면 변경사항이 좀 더 적은 상태로 PR 머지가 가능할 것 같습니다.

2022-09-16 08:16 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +                        if "Layer0." in coll_child.name:
일단 이게 코드로 보면 import의 속도를 느려지게 할 원인중에 하나로 "보이기는"합니다만, 어차피 이후의 방향성으로는 Layer0가 사라질 예정이라 backward compatibility의 측면에서 들어가도 괜찮은 것 같긴 합니다!

2022-09-16 08:16 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +            # 레이어 이름에 Layer0.이 포함된 중복 레이어 제거
이부분과 duplicate_layer의 존재자체가 오버엔지니어링이 아닌가 생각은 들어요. `Layer0.`이 들어가는 콜렉션이 n개 이상인 케이스가 이 변경사항 이후에도 빈번하게 일어날까요?

2022-09-16 08:16 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +            tracker.import_blend_fail()
트래커의 종류를 하나 더 추가하는게 좋지 않을까 생각되네요. 한 에러당 한 트래커

예: `tracker.same_file_import_error()`

2022-09-16 08:18 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +            tracker.import_blend_fail()
추후 논의되어야 할 사항 같지만, 종류를 추가하지 않고 파라미터로 에러 사유 세분화해서 믹스패널로 보내는 것도 괜찮을 것 같습니다!

2022-09-16 08:53 UTC, habijung commented on release/scripts/startup/abler/general.py
> -            FILEPATH = self.filepath
해당 사항 반영했습니다!

2022-09-16 08:53 UTC, habijung commented on release/scripts/startup/abler/general.py
> -
해당 사항 반영했습니다!

2022-09-16 09:02 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            tracker.import_blend_fail()
일단, 기존의 트래커 이름과 유사하게 `tracker.import_same_blend_fail()` 로 정의해서 추가했습니다.

2022-09-16 09:34 UTC, habijung commented on release/scripts/startup/abler/general.py
> +            # 레이어 이름에 Layer0.이 포함된 중복 레이어 제거
`duplicate_layer` 가 중복되는 레이어 전체를 관리하기 위해서 만들었었는데, `Layer0.xxx` 으로 한정되면서 빠져도 되는 부분을 미처 인지하지 못했습니다.
`Layer0.xxx` 만 처리를 위해 해당 리스트를 지우고, 과정을 간소화하였습니다.

2022-09-17 06:40 UTC, habijung commented on release/scripts/startup/abler/general.py
> +                        if "Layer0." in coll_child.name:
Layer0 레이어가 없어지면 속도가 많이 줄 것 같습니다!
간단하게 테스트를 해봤는데, 용량이 큰 두 파일을 Open (약 90MB) -> Import (약 280MB) 해봤습니다.

- **환경별 속도 측정 (`cProfile.run`)**
    - Alienware R15
        - `ABLER/main`: 약 1500초
        - `feature/import-duplicate-layer`: 약 1900초
    - Mac Mini (M1)
        - `ABLER/main`: 1028.29초
        - `feature/import-duplicate-layer`: 815.82초

너무 큰 파일은 Import 가 오래 걸리고 있어, 추후에 수요가 많아질 경우 속도 개선 작업이 이루어져야 할 것 같습니다!

2022-09-19 04:50 UTC, sdkfile approved these changes
수정사항 확인해서 어프룹 드립니다!

2022-09-19 05:49 UTC, merged