파일 더블클릭으로 에이블러 업데이트 시, 파일 경로에 blendtemp(다운로드 파일) 이 쓰여짐
ACON3D/blender pull request #156
Opened 2022-09-23 05:39 UTC by sdkfile

## 관련 링크
[이슈 링크](https://www.notion.so/acon3d/Issue-0048-blendtemp-f9d282da4048461587c280d21967a33f)

## 발제/내용

- blendtemp 가 0.2.4 버전 파일 path에 blendertemp 파일이 다운로드됨
- 업데이트 완료 이후에 각 폴더 / zip파일 삭제
![image](https://user-images.githubusercontent.com/43770096/191897994-a71cc2f9-bf08-4995-b1e9-d430c2deff37.png)

## 대응

### 어떤 조치를 취했나요?
- launcher의 temp 폴더 위치를 AblerLauncher.exe의 위치로 정해줌

2022-09-26 09:33 UTC, habijung approved these changes
왜 안되지? 하고 있었는데, 런처를 `.exe` 로 만들어서 바꿔줬어야 했네요.
빌드 후 테스트하고 문제 없어서 어프룹입니다!

2022-09-26 09:58 UTC, habijung requested changes
@sdkfile 
이 PR 전후로 런처에서 Download UI는 잘 넘어가는데, 새 버전 다운로드가 안되고 있어서 내일 (09.27 (화)) 한번 더 확인 가능하실까요?

2022-09-28 05:17 UTC, sdkfile commented
@habijung 요청사항 수정 + 컨플릭트 해결까지 완료했습니다 리뷰 부탁드릴게요!

2022-09-29 04:21 UTC, habijung approved these changes
수정 사항 및 동작 같이 확인해서 어프룹입니다!

2022-09-29 04:24 UTC, merged