Scene 변경 시 Scene 마다 l_exclude 갯수가 다를 때 발생하는 에러
ACON3D/blender pull request #180
Opened 2022-10-13 08:24 UTC by Youdiie

## 관련 링크
[링크](https://www.notion.so/acon3d/Scene-Scene-l_exclude-d422200fa53d474395abacf5f0d39920)

## 발제/내용

- 씬마다 레이어 갯수(l_exclude)가 달라 씬 전환시 handle_layer_visibility_on_scene_change 과정에서 에러 발생

## 대응

### 어떤 조치를 취했나요?

- 이전 씬의 l_exclude의 i가 새 씬의 l_exclude 총 갯수보다 넘어갈 때 처리하지 않고 패스하도록 코드 추가했습니다.

2022-10-13 08:30 UTC, Youdiie commented
노션 링크에 에러 발생하는 파일 첨부해두었습니당

2022-10-14 00:10 UTC, JJong84 requested changes
oldScene 과 newScene 의 l_exclude 개수가 달라지는 경우가 일반적으로 자주 발생하는 경우일까요?

해당 작품 확인해보니까 뭔가 이상한 레이어들이 '콘티'라는 씬에 붙어있네요..

2022-10-14 02:11 UTC, Youdiie commented on release/scripts/startup/abler/lib/layers.py
> +            continue
헉 그렇네용

2022-10-14 02:13 UTC, Youdiie commented
> oldScene 과 newScene 의 l_exclude 개수가 달라지는 경우가 일반적으로 자주 발생하는 경우일까요?
> 
> 해당 작품 확인해보니까 뭔가 이상한 레이어들이 '콘티'라는 씬에 붙어있네요..

아마 모델러가 Scene 씬에서 FBX파일을 import해서 그런거 같습니다.
만약 모델에 A,B,C 씬이 있고 B에서 import(blend, fbx 모두)하면 l_exclude가 늘어나는데 A,C 씬에선 변함이 없어 요런 현상이 발생할 순 있을거 같네용

2022-10-14 02:24 UTC, JJong84 commented
> > oldScene 과 newScene 의 l_exclude 개수가 달라지는 경우가 일반적으로 자주 발생하는 경우일까요?
> > 해당 작품 확인해보니까 뭔가 이상한 레이어들이 '콘티'라는 씬에 붙어있네요..
> 
> 아마 모델러가 Scene 씬에서 FBX파일을 import해서 그런거 같습니다. 만약 모델에 A,B,C 씬이 있고 B에서 import(blend, fbx 모두)하면 l_exclude가 늘어나는데 A,C 씬에선 변함이 없어 요런 현상이 발생할 순 있을거 같네용

@Youdiie 
오 이거 에이블러 버그 같네요. 저도 지금 가져오기로 .blend 파일 가져와보니까 해당 씬에서만 레이어가 늘어나네요..
Import 시에도 모든 씬에 레이어 추가하는 작업이 필요해보입니다!

2022-10-14 04:12 UTC, Youdiie commented
엑 리뷰어 잘못눌렀네요

2022-10-14 05:44 UTC, JJong84 approved these changes
어프룹드리겠습니다! 고생하셨습니다!

회의 떄 나왔던 하위호환성 관련된 이야기만 노션에 남겨주시면 좋을 것 같습니다. :)

2022-10-14 06:24 UTC, sdkfile approved these changes
ㅇㅈ합니다

2022-10-14 06:25 UTC, merged