export 탭 UI 정리 및 리팩토링
ACON3D/blender pull request #192
Opened 2022-10-19 08:04 UTC by sdkfile

## 관련 링크
[노션 태스크 링크](https://www.notion.so/acon3d/Export-0b4f7b66aaeb44d5afbce1bed20d97dd)

## 발제/내용

- 아래의 기획과 현재 Render 기능이 차이가 커서, 해당 내용을 수정 및 추가개발하고자 함.
[기획 링크](https://www.notion.so/acon3d/Export-0b4f7b66aaeb44d5afbce1bed20d97dd#af1fba3a4bb447f191758dc8973c2e4b)

## 대응

### 어떤 조치를 취했나요?

- [ ] UI 작업중

2022-10-20 02:27 UTC, JJong84 commented on release/scripts/startup/abler/custom_properties.py
> +    is_selected: bpy.props.BoolProperty(
is_selected 는 렌더 탭에서 렌더 대상을 선택할 때만 사용되는 것인가요?

2022-10-20 02:27 UTC, JJong84 commented on release/scripts/startup/abler/custom_properties.py
> +    hq_render_full: bpy.props.BoolProperty(name="Full Render", description="asdf")
description 은 나중에 설명 추가되는 걸까요?

2022-10-20 02:27 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/export_control.py
> +            row.prop(scene.render, "resolution_x", text="")
resolution 변경하는 부분이 렌더마다 있는데, 한 부분만 변경해도 모든 부분이 동일하게 변경하는 버그가 발생할 것 같습니다!

2022-10-20 02:27 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
> +    # Acon3dRenderPanel,
폭력적으로 지워도 문제 없을 것 같습니다!

2022-10-20 02:27 UTC, JJong84 commented on release/scripts/startup/abler/custom_properties.py
> +    is_selected: bpy.props.BoolProperty(
지금 당장은 아니지만, 추후에 psd export 등이 추가되게 되면 해당 부분도 이 부분과 비슷한 로직이 들어가게 될 것 같은데,
그 때를 대비해서 미리 이름을 `is_render_selected` 이런 식으로 변경해두면 좋을 것 같습니다

2022-10-20 02:31 UTC, sdkfile commented on release/scripts/startup/abler/custom_properties.py
> +    hq_render_full: bpy.props.BoolProperty(name="Full Render", description="asdf")
네네 세부사항은 아직 잡지 않았어요!

오늘 그냥 사양서 보고 한번 작업해볼게요

2022-10-20 02:31 UTC, sdkfile commented on release/scripts/startup/abler/custom_properties.py
> +    is_selected: bpy.props.BoolProperty(
좋아요 반영해볼게요~

2022-10-20 02:32 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/export_control.py
> +            row.prop(scene.render, "resolution_x", text="")
어 저는 그거 버그 아닌 것 같아요. 카메라 속성이라 당연히 동일하게 변할꺼고, 뷰도 변할 예정이라 그대로 유지하는걸로 알고 있습니다

2022-10-20 02:32 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +    # Acon3dRenderPanel,
넵 좋슴다

2022-10-21 08:20 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
> +            if self.render_name_queue and self.render_name_queue[0]:
self.render_name_queue 에 empty list 인지 체크하는 조건도 들어있기 때문에
self.render_name_queue 만 조건으로 넣어도 될 것 같습니다!

2022-10-21 08:20 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
> +                if self.render_name_queue and self.render_name_queue[0]:
위와 동일합니다..!

2022-10-21 08:20 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
>          self.render_queue.append(scene)
queue 두 개 모두 동일한 부분에서 삽입/삭제 가 이루어지는 것 같은데,
하나의 queue 로 묶고 내부 데이터를 tuple 로 (scene, str) 관리하는 것은 어떨까요?

None 일 때 처리나, 삽입/삭제 처리 시 더 명확할 것 같습니다.

2022-10-21 10:10 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +            if self.render_name_queue and self.render_name_queue[0]:
오 아니에요 그렇게 넣으니깐 세그폴트 뜨면서 죽더라고요 그래서 넣음

2022-10-21 10:11 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
>          self.render_queue.append(scene)
그러기에는 변경사항이 많은 것 같아서 일단 그렇게 해놓기는 했는데, 한번 생각해볼게용

2022-10-25 00:35 UTC, JJong84 requested changes
1. Warning, Save Operator 둘 다 description 넣으면 좋을 것 같습니다!
![스크린샷 2022-10-25 오전 9 31 57](https://user-images.githubusercontent.com/39782865/197655186-b3c3d614-0648-48c3-a40f-fd665b70bb22.png)

2.  Warning Modal 에서 Cancel 에 마우스를 올리면 모달이 갑자기 가운데로 이동하는데 고치는 것이 가능할까요?

2022-10-25 00:35 UTC, JJong84 commented on release/scripts/startup/abler/startup_flow.py
> +        is_scene_selected = any(s.is_render_selected for s in render_prop.scene_col)
scene_count > 0 로 변경하면 좋을 것 같습니다!

(아니면 182번째 줄의 scene_count 를 없애고 for 문 돌게 변경해도 될 것 같습니다)

2022-10-25 00:49 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
>          self.render_queue.append(scene)
아 이거 까먹었다 ㅎㅎ

2022-10-25 09:22 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +                if self.render_name_queue and self.render_name_queue[0]:
아래 변경사항 작업하면서 해결됨

2022-10-25 09:22 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +            if self.render_name_queue and self.render_name_queue[0]:
마찬가지

2022-10-25 09:22 UTC, sdkfile commented on release/scripts/startup/abler/startup_flow.py
> +        is_scene_selected = any(s.is_render_selected for s in render_prop.scene_col)
이거는 일단 세그폴트 뜨는거 먼저 해결하고 볼게용

2022-10-26 01:44 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
> +                qitem = self.render_queue[0][1]
qitem, name_item = self.render_queue[0]
같은 형식으로 값을 가져오면 데이터에 접근하는 횟수를 줄일 수 있을 것 같습니다!

2022-10-27 07:50 UTC, sdkfile commented on release/scripts/startup/abler/startup_flow.py
> +        is_scene_selected = any(s.is_render_selected for s in render_prop.scene_col)
완료입니다 @JJong84

2022-10-27 07:51 UTC, sdkfile commented
@JJong84 세그폴트, render_queue 튜플로 관리, scene_count로 poll 검증 이렇게 세가지 해결했습니다!

2022-10-27 07:51 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +                qitem = self.render_queue[0][1]
오 이것도 지금 해결하러 갑니다

2022-10-27 07:57 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +                qitem = self.render_queue[0][1]
완료

2022-10-27 08:00 UTC, sdkfile commented
description은 넣는 방향으로 수정해야겠네요

2022-10-27 08:01 UTC, JJong84 commented
여기까지 리뷰 완료했습니다~!! @sdkfile

2022-10-27 10:52 UTC, sdkfile commented
@JJong84 뭔가 해결 난이도가 조금은 낮아보이는 버그를 하나 발견해서, 그거 해결한 다음에 또 알려드릴게요~

2022-10-28 02:28 UTC, sdkfile commented
@JJong84 버그 완 벽 수 정

2022-10-28 02:45 UTC, JJong84 commented
@sdkfile 여기까지 확인 완료했습니다!
여기서부터 크게 변하는 것 없으면 브랜치 새로 만들어서 제가 하던 렌더 작업 이어가보겠습니다!

2022-11-04 04:52 UTC, sdkfile commented
@JJong84 혹시 여기서 더 작업을 하고 계신 부분이 있는거죠??

2022-11-08 06:52 UTC, JJong84 commented
- [x]  렌더 중일 때 UI 가 어는 문제 해결하기
    HQ 렌더 외에 다른 UI 가 다시 그려지지 않아서 겹쳐서 보이는 오류가 있어서 렌더 전에 미리 공간을 확보하는 작업을 함
    - `is_loaded` 라는 변수를 두고, 해당 변수를 씬 개수를 알 수 있는 때부터 실제 렌더 시작 전까지 True, 그 외에는 항상 False
    - 위 변수가 True 일 때 스켈레톤 UI 를 그리도록 함.
        - 순간적으로 값이 잠깐 변해서 UI 가 잘 그려지지 않는 것 같아서 `bpy.app.timers.register(self.render_handler, first_interval=0.01)`
        를 통해 다음 루프에 그리도록 함.
        - `first_interval=0` 으로 하면 약간 잘리는 이슈가 있어서, 값을 넣으니까 동작하는 것을 확인
- [x]  저장 관련 플로우 개선
    - 저장이 필요할 때 저장이 제대로 되지 않는 이슈가 있었음
    - 기존 저장과 같이 mixpanel tracking, recent files list 갱신이 필요함
    - `render_save_handler` 에서 hq render 실행, 이 핸들러를 `save_post` 에 등록해서 저장 후 hq render 가 실행되도록 함.
    - `render_save_handler` 는 저장 후 렌더 동작 때만 실행될 수 있도록 실행 후 바로 `save_post` 에서 삭제
    - 필요가 없어진 `is_rendered` 삭제

2022-11-08 07:12 UTC, sdkfile reviewed
이거 제가 pull request 처음으로 만든 사람이라 어프룹은 못하네요 ㅎㅎ

2022-11-08 07:14 UTC, JJong84 approved these changes
(제가 쓰긴 했지만) 어프룹드리겠습니다~

2022-11-08 07:14 UTC, merged