에이블러 메뉴 내 에이블러 미필요 기능 비활성화
ACON3D/blender pull request #193
Opened 2022-10-20 07:10 UTC by habijung

## 관련 링크

[태스크 카드](https://www.notion.so/acon3d/92196c8f7ef64e258d33666bdf31a9a1)
[에이블러 I.A.](https://docs.google.com/spreadsheets/d/1ClMV5ObLBfgqiRhaz3yLiViSret5GcYqU-k_vdvSj_c/edit#gid=1235797135)

## 발제/내용

- 현재 에이블러 내에서 제공하지 않는 기능이 많아서 필요 없는 기능들을 정리할 필요가 있음.

## 대응

### 어떤 조치를 취했나요?

- 메뉴 항목 삭제
  - 에이블러 I.A. 기준으로 삭제함
- Import 기능은 addons 설정이 포함되어 있어, 필요한 Import 기능 메뉴를 따로 추가함
- Manul 및 Support 링크를 에이블러 링크로 변경

### TODO

- 나중에 `Import` 기능이 완성되면 오퍼레이터를 알맞게 연결하는 작업이 필요함.

2022-10-20 08:18 UTC, JJong84 requested changes

2022-10-20 08:19 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    for addon in addons:
요거 함수로 묶고 lib 폴더 내 파일에서 관리합시다!

2022-10-20 08:19 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP"]
오잉 중국어도 1:1 있어요!
https://www.acon3d.com/zh/toon/inquiry/write

2022-10-20 08:19 UTC, Youdiie commented on release/scripts/startup/bl_ui/space_topbar.py
> +class TOPBAR_MT_ACON3D_file_import(Menu):
으악 여기 주석 넣는다는걸 깜빡했네요
왜 ACON3D 클래스로 또 만들었는지 추가할께요~

2022-10-20 08:25 UTC, Youdiie commented on release/scripts/startup/abler/general_tab/general.py
> +
맞습니다!

2022-10-20 08:26 UTC, Youdiie commented on release/scripts/startup/abler/general_tab/general.py
> +    filter_glob: bpy.props.StringProperty(default="*.fbx", options={"HIDDEN"})
요건 ImportSKP 때 까먹지 않고 넣는걸로 가시죵

2022-10-20 08:27 UTC, Youdiie commented on release/scripts/startup/abler/general_tab/general.py
> +    filter_glob: bpy.props.StringProperty(default="*.fbx", options={"HIDDEN"})
는 워니님 드라이버네요 ㅎ

2022-10-21 02:41 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP"]
사양서에는 중국어 관련 내용이 따로 없어서 추가를 안했는데, 해외 오픈도 되어서 추가하는게 좋을 것 같네요.
추가 후에 Resolve 하겠습니다.

2022-10-21 04:58 UTC, habijung commented on release/scripts/startup/abler/pref.py
> +    for addon in addons:
`lib` > `addons.py` 로 파일 따로 만들었습니다~

2022-10-21 05:07 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
languages 도 locale_names 같은 형식으로 이름 바꿔서 함수 내가 아니라 파일로 따로 관리하는 것도 좋아보입니다!

2022-10-21 05:09 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
`wm.py` 파일은 `abler` 폴더의 바깥 (`bl_operators`) 에 속하고 있어 따로 처리하기에는 더 복잡할 것 같아서 특별한 조치를 취하지 않았습니다. 그럼에도 따로 분리를 하는게 더 괜찮을까요?

2022-10-21 05:11 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
나라 코드 같은 경우에는 추후에 다른 곳에서 사용될 수 있는 여지가 있는 것 같아서 파일 따로 분리는 어렵더라도 전역 변수로 두는 것도 좋을 것 같습니다!

2022-10-21 05:53 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
전 이번 턴에선 따로 분리하지 않고 추후에 더 많은 언어를 지원할 때 전역변수 혹은 파일 분리를 해도 될거 같아요!
이 태스크에선 비활성화가 주 목적이니 너무 범위가 넘어가지 않는게 태스크 관리 측면에서 좋을거 같습니당

2022-10-21 05:54 UTC, Youdiie approved these changes
저도 개발에 참여했지만 어프룹도 누르겠슴닷!

2022-10-21 06:16 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
```
startup
  > abler
      > lib
          - locales.py
  > bl_operators
      - wm.py
```

에이블러에 사용되는 변수나 함수들을 `lib` 내부에 보통 모아준다고 생각해서 옮기려고 하니, 상위 폴더 `import` 가 필요해서 지금 바로 만들어주는 것보다, 저도 비슷하게 추가 언어가 생겨서 언어 지원이 더 필요할 때 (필요 시에) 추가 작업이 들어가도 좋다고 생각합니다!

2022-10-21 06:21 UTC, sdkfile requested changes
약간의 변경사항 요청과 코멘트 달아두었습니다.

2022-10-21 06:21 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
아니면 저는 에이블러에서 지원하는 locale을 따로 ACON_prop에 넣는것도 좋은 방법인 것 같아요.

그러면 wm.py에서든 어디서든 호출할 수 있잖아요? ㅎㅎ

2022-10-21 06:21 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +notices = ('READY', None)
여기 변경사항은 없어도 될 것 같아요.

2022-10-21 06:21 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +
이곳도 마찬가지로 변경사항 없애주세용

2022-10-21 06:37 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +notices = ('READY', None)
Black 적용도 안하고 Sublime Merge에서도 공백 Show로 되어있는데도 잡히지 않았어서 그냥 지나갈뻔 했네요. 확인 감사합니다~

2022-10-21 06:40 UTC, JJong84 commented
@sdkfile @habijung

> 아니면 저는 에이블러에서 지원하는 locale을 따로 ACON_prop에 넣는것도 좋은 방법인 것 같아요.

Acon_Prop 으로 넣으면 파일마다 저장이 되진 않을까요?
파일에 저장할 필요는 없을 것 같고 프로그램 내에서만 존재하게 하려면 전역 변수로 넣는 것이 좋을 것 같습니다..!

2022-10-21 06:56 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
정의된 `languages` 변수는 파일 혹은 프로그램의 속성이 아닌 단순 `preferences` 값과의 비교를 위해서 미리 세팅해준 변수인데, `ACON_prop` 으로 들어가는 것이 정의된 변수의 의도를 살짝 벗어난 것 같습니다.
그렇다면, `bl_operators` 내부에 `lib` 폴더를 하나 새로 만들어서 해당 폴더 내부에서 전역으로 관리하는 것이 좋을 것 같습니다.

2022-10-21 07:25 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
아니다 그냥 .env에 넣어서 os.getenv("supported_language") 이렇게 들어가는게 좋지 않을까요?

2022-10-24 04:41 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    languages = ["ko_KR", "en_US", "ja_JP", "zh_CN", "zh_TW"]
이 부분을 아래의 구조로 `abler` > `lib` 폴더에서 한번에 관리할 수 있도록 수정했습니다.
```
startup
  > abler
      > lib
          - locales.py
  > bl_operators
      - wm.py
```
`wm.py` 에서는 상대 경로 `import` 가 불가능해서 (터미널 결과) parent directory 를 찾아서 추가해주는 과정을 Windows 와 Mac 에서 각각 처리했습니다.

2022-10-24 06:28 UTC, sdkfile requested changes
매우 작은 코멘트 하나가 있습니다. 이부분 해결되면 마무리되어도 괜찮을 것 같아요

2022-10-24 06:28 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        # Import ABLER lib directory
이곳에 주석을 조금 더 잘 적어주셨으면 좋겠습니다! @habijung

2022-10-24 06:39 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +        # Import ABLER lib directory
이 부분 설명 추가했습니다!

2022-10-24 06:42 UTC, sdkfile reviewed
@habijung 관련 없는 변경사항이 들어가있어서 코멘트 달았습니다~

2022-10-24 06:42 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +notices = ('READY', None)
여기에 다시 쓸모없는 변경사항이 들어가있어요 @habijung

2022-10-24 06:42 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +
여기도 마찬가지입니다~

2022-10-24 06:43 UTC, habijung commented
> @habijung 관련 없는 변경사항이 들어가있어서 코멘트 달았습니다~

관련 부분 또 실수를 했네요. 해당 부분 제외하고 다시 push 했습니다. 확인 감사합니다~

2022-10-25 02:03 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +        if sys.platform == "win32":
처음에는 가볍게 파일 위치에서 임포트하면 되지 않을까 생각했는데, 생각보다 많이 복잡했네요... 고생하셨습니다
혹여나 오버엔지니어링이 되지 않을까 걱정이 드는데, 다른 분들 의견을 여쭤봐도 될까요?

2022-10-25 04:56 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +        if sys.platform == "win32":
[슬랙 쓰레드] (https://acontainer.slack.com/archives/CTHPPE3LM/p1666663399340299)
위 쓰레드에서의 논의에 따라 유지하기로 하였습니다.

2022-10-25 04:56 UTC, JJong84 approved these changes
어프룹 드리겠습니다! 고생하셨습니다!

2022-10-25 05:05 UTC, sdkfile approved these changes
저도 어프룹 드리겠습니다!

2022-10-25 05:07 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +        if sys.platform == "win32":
아카이브 감사합니다!

2022-10-25 06:48 UTC, merged