import skp에 대한 프로그레스 바 작업
ACON3D/blender pull request #245
Opened 2022-11-17 06:29 UTC by JJong84

## 관련 링크
[태스크 카드](https://www.notion.so/acon3d/import-skp-5a42ff60e5c24514b8c921e2db493502)
[io_skp 작업 PR1](https://github.com/ACON3D/SKP_Converter/pull/91)
[io_skp 작업 PR2](https://github.com/ACON3D/SKP_Converter/pull/93)

## 발제/내용

- 에이블러에 skp 임포트 기능을 넣는다.

## 대응

### 어떤 조치를 취했나요?

-

2022-11-17 10:13 UTC, sdkfile requested changes
뒷 연산은 내일까지 수정 예정이라고 하셔서, UI 부분만 리뷰 남겨봤습니다~ @JJong84

2022-11-17 10:13 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> +        sub = box.split(align=True, factor=0.25)
![Screenshot 2022-11-17 at 7 02 19 PM](https://user-images.githubusercontent.com/43770096/202417016-0412ea7b-4ce7-4040-be45-2b9f083115f0.png)

위와 같이 Label들이 잘려서 보이는 경향성이 있어요. 비율을 조금 조정해보는게 좋지 않을까요?
물론 화면 사이즈마다 다르겠지만, 제가 빌드해보기로는 저희 작업하는 맥북 (13인치와 16인치 모두 포함하여) 에서 다 잘리는 것 같아서, 조금 조정해봐요!

2022-11-17 10:13 UTC, sdkfile commented on release/scripts/startup/abler/lib/utils.py
> +from time import strftime, localtime, gmtime
이 파일이 util로 이름지어지는게 직관적이지 않다는 생각입니다. lib 폴더의 다른 파일들은 조금 더 직관적인 것 같아서, 아니면 `string_helper` 등 (급조해서 매력적이진 않은 것 같지만)이 어떨까 싶어요.

2022-11-17 10:13 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> +    progresses = (
`prop`에 모든 값들이 잘 들어가있는지에 대한 방어구문이 들어가있지 않은 것 같아요 추가해봅시다!

2022-11-17 10:13 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> -
이것은 black인가 필요없는 변경사항인가 그것이 문제로다

2022-11-18 01:03 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> +        sub = box.split(align=True, factor=0.25)
Label 크기를 늘리면 Date 가 잘려서 일단 Date 를 보여주는 게 더 중요할 것 같아서 저 정도로 잡았던 것 같습니다!
아예 사이드메뉴 너비를 늘리는 건 어떨까요?

2022-11-18 01:04 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> +    progresses = (
이 부분은 코드 변경하면서 사라지는 내용입니다~!

2022-11-18 01:06 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> -
이 부분은 롤백하겠습니다!

2022-11-18 01:11 UTC, JJong84 commented
@sdkfile 리뷰 주신 것 관련해서 댓글 남겼습니다!

2022-11-18 01:11 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> +        sub = box.split(align=True, factor=0.25)
이 부분은 렌더 쪽도 똑같이 있는 이슈일 텐데 날짜를 없애고 시각만 남기는 방안도 고려볼 수도 있을 것 같습니다. (기획셀과 상의 후)

2022-11-18 01:17 UTC, seungha-kim commented on release/scripts/startup/abler/general_tab/general.py
> +        sub = box.split(align=True, factor=0.25)
저는 시각만 남기는 방안 찬성입니다~~

2022-11-18 01:19 UTC, seungha-kim approved these changes
저는 `...` 생기는 것 제외하고는 선 어프룹입니다! 고생 많으셨어요!

2022-11-18 01:20 UTC, JJong84 commented
> 저는 `...` 생기는 것 제외하고는 선 어프룹입니다! 고생 많으셨어요!

@seungha-kim @sdkfile ... 생기는 건 렌더쪽도 마찬가지니까 다른 브랜치에서 처리하는 것이 좋을 것 같습니다!

2022-11-18 01:23 UTC, JJong84 commented
@sdkfile 
파일 이름 변경 및 newline 처리해서 다시 푸쉬했습니다.

2022-11-18 02:07 UTC, Youdiie approved these changes

2022-11-18 02:08 UTC, habijung approved these changes
설명 세션 가져서 바로 어프룹입니다!

2022-11-18 02:09 UTC, merged