그림자 렌더가 제대로 작동하지 않는 문제
ACON3D/blender pull request #279
Opened 2022-12-12 08:29 UTC by JJong84

## 관련 링크
[태스크](https://www.notion.so/acon3d/ccaebd5b20ab433686d4c8ca7eb57192)
[이슈](https://www.notion.so/acon3d/Issue-0123-a9ed7aa483074ffe981e163663ec9184)

## 발제/내용

- 그림자 렌더할 떄, 투명 재질이 있으면 해당 부분의 렌더가 제대로 동작하지 않음.

## 대응

### 어떤 조치를 취했나요?

- Shadow Render 의 material 에 blend_method, shadow_method 가 OPAQUE 모드로 들어가면, 투명 재질로 인해 렌더링이 이상하게 보임
- 기존에 적용시키던 OPAQUE 를 Line Render 시에만 적용하고, 그 외에는 `materials_handler.set_material_parameters_by_type(mat)` 함수를 사용하도록 함

2022-12-12 08:34 UTC, sdkfile approved these changes
저는 코드 같이 봤는데, 제대로 작동하는 것도 방금 한번 더 확인했습니다.

2022-12-12 09:14 UTC, Youdiie requested changes

2022-12-12 09:14 UTC, Youdiie commented on release/scripts/startup/abler/export_tab/render_control.py
> +                materials_handler.set_material_parameters_by_type(mat)
원래 코드에선
```
if toonNode := mat.node_tree.nodes.get("ACON_nodeGroup_combinedToon"):
                    toonNode.inputs[1].default_value = 0
                    toonNode.inputs[3].default_value = 1
```
요 내용이 있었는데 `materials_handler.set_material_parameters_by_type(mat)` 함수 내부의 코드와 달라 출력물이 다르게 나옵니다. 확인 부탁드립니다

2022-12-12 09:14 UTC, Youdiie commented on release/scripts/startup/abler/export_tab/render_control.py
> +                materials_handler.set_material_parameters_by_type(mat)
// 이전 쉐도우 렌더
![Coni's room_shadow 001](https://user-images.githubusercontent.com/87409148/207006789-478f4fb5-d5b0-42e8-baa2-50cebb5cc4b7.png)
// 변경된 코드의 쉐도우 렌더
![Coni's room_shadow 001](https://user-images.githubusercontent.com/87409148/207006783-3fd30bda-d865-429b-b4a9-46cce2e075fa.png)

2022-12-13 00:18 UTC, JJong84 commented on release/scripts/startup/abler/export_tab/render_control.py
> +                materials_handler.set_material_parameters_by_type(mat)
앗 조건 다시 짜야겠군요.. 확인했습니다! @Youdiie

2022-12-13 00:40 UTC, JJong84 commented
이 부분 다시 생각해보니, full 렌더 하는 경우에 pass 를 해버리면 이전 렌더의 재질 설정이 그대로 들어가버려서 full 렌더도 else 에 포함되게 해야할 것 같습니다!

@Youdiie @sdkfile

2022-12-13 00:41 UTC, sdkfile commented
> 이 부분 다시 생각해보니, full 렌더 하는 경우에 pass 를 해버리면 이전 렌더의 재질 설정이 그대로 들어가버려서 full 렌더도 else 에 포함되게 해야할 것 같습니다!
> 
> @Youdiie @sdkfile

생각해보니 어차피 render_finish가 있어서 마지막에는 재질 걱정을 안해도 되는거군요

2022-12-13 05:10 UTC, JJong84 commented
@Youdiie @sdkfile 논의사항대로 반영하여 새로 커밋 올렸습니다~ 확인하고 리뷰해주시면 감사하겠습니다!

2022-12-13 07:01 UTC, Youdiie approved these changes
어프룹입니다! 고생많으셨어요

2022-12-13 07:15 UTC, sdkfile approved these changes
저도 확인했습니다! 고생하셨습니다 모두!

2022-12-13 07:21 UTC, merged