[온보딩 프로젝트] Cube 패널 추가 후 Cube를 Control하는 버튼 추가
ACON3D/blender pull request #282
Opened 2023-01-20 07:46 UTC by HaYeonKim00

## 발제/내용

- 온보딩 프로젝트로 Cube라는 패널을 생성한 후, 그 안에 cube를 control하는 버튼들을 추가함. 

## 패널에 추가한 기능

### 1. Add Cube/ Delete All
- ``add cube``클릭 시, 생성되는 큐브의 위치와 이름을 지정할 수 있음. 
- 생성되는 큐브에 랜덤으로 색상이 지정됨. 
- ``delete all``클릭 시, 화면의 모든 개체가 삭제 됨. 
### 2. Move Cube/ Scale Cube/ Rotate Cube
- 슬라이더를 이용해 개체의 위치와 크기를 조정하고 회전할 수 있음. 

## 보완해야 할 부분

### 선택한 cube의 현재 위치를 불러와서 슬라이더에 적용할 수 있음.
- 현재 상태에서는 슬라이더로 변화시킨 값만 저장되어 기즈모를 이용해 cube를 직접 움직인 경우 그 값이 슬라이더에 반영되지 않음.

2023-01-20 07:48 UTC, sdkfile commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    def draw(selfo, context):
오타 있어용

2023-01-25 01:39 UTC, sdkfile commented on release/scripts/startup/abler/cube_tab/create_cube.py
> +import random
이 모듈 블렌더에서 사용하기 어려우셔서 abler_requirements.txt에 넣었다고 하지 않으셨나요? 아니라면 넘어가주세용
@HaYeonKim00

2023-01-25 01:49 UTC, sdkfile requested changes
질문과 개선사항 남겨드렸습니다 @HaYeonKim00

2023-01-25 01:49 UTC, sdkfile commented on release/scripts/startup/abler/custom_properties.py
> +        default=1,
스케일에만 default 값이 있는 이유가 무엇인가요?

2023-01-25 01:49 UTC, sdkfile commented on release/scripts/startup/abler/lib/objects.py
> +def edit_state(self, context):
이 함수 하나로 translation / rotation / scale 세 가지가 모두 한번에 컨트롤 되는 것이 비효율적으로 보입니다. 

하나의 파라미터 변경으로 이 함수 안에 있는 모든 구문이 실행되어야 하는 것이 비효율적인 구조라고 생각되어서요. 최소한 (+ 가독성을 위해서) translation / rotation / scale 이렇게 세가지는 update function이 구분이 되어있어야 하지 않나 생각됩니다!

2023-01-25 01:49 UTC, sdkfile commented on release/scripts/startup/abler/custom_properties.py
> +    def get_location_x(self, context):
이 함수는 쓰임이 없는 것 같은데 혹시 어디서 쓰이고 있을까요?

2023-01-25 02:04 UTC, Youdiie requested changes

2023-01-25 02:04 UTC, Youdiie commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
요 구문 자체가 for문으로 선택된 오브젝트마다 적용하는데 아래의 context.active_object에서 active_object인 오브젝트만 적용한다고 하네요? selected_objects와 active_object는 차이를 찾아보시고 실제 선택된 오브젝트 '하나'만 변경될 수 있도록 수정 부탁드립니다!

2023-01-25 02:55 UTC, HaYeonKim00 commented on release/scripts/startup/abler/custom_properties.py
> +    def get_location_x(self, context):
삭제했습니다!

2023-01-25 02:57 UTC, HaYeonKim00 commented on release/scripts/startup/abler/custom_properties.py
> +        default=1,
처음에 만들어질때 scale에 default 값을 두지 않으면 location 이동을 먼저하거나 rotate을 하려고 할 때 scale = 0 인 값이 적용 되면서 cube가 사라져서요! 사실 현재 큐브의 location, scale, rotate의 값을 가져올 수 있으면 없어도 되는 값입니다.

2023-01-25 03:19 UTC, sdkfile approved these changes
저는 온보딩 태스크에서는 이정도 봐도 괜찮을 것 같습니다!

2023-01-25 03:19 UTC, sdkfile commented
> 저는 온보딩 태스크에서는 이정도 봐도 괜찮을 것 같습니다!

다만 위에 남겨진 다른 태스크의 커밋은 없애주세요! @HaYeonKim00

2023-01-25 04:02 UTC, Youdiie commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
@HaYeonKim00 요건 변경안된거 같아용

2023-01-25 04:08 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
for loop 안에 obj = active object 이 부분 삭제했습니다. 확인해보니 active object는 선택된게 없으면 이전에 선택했던 개체를 리턴해서 selected_objects를 쓰는게 맞다고 생각했고 그게 none이지 않을 경우만으로 해서 선택된게 없을 때에는 작동 안하게 그렇게 했습니다. 이게 맞을까요?

2023-01-25 04:15 UTC, Youdiie commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
for 문을 쓰면 개체를 여러개 선택했을 때 모두 같이 움직입니다. 다같이 움직이는걸 의도하신걸까요?

2023-01-25 04:19 UTC, JJong84 commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
edit_state_XXX 함수는 하나의 object 가 update 될 때만 쓰이는데, 이 대상 object 는 이미 `self` 를 통해서 레퍼런스를 가져오고 있기 때문에 for 문으로 현재 선택된 오브젝트가 있는지 체크할 필요는 없지 않을까요?
혹시 for 문 넣으신 다른 이유가 있을까요?

2023-01-25 06:24 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
네! for문은 그래서 쓴거 맞습니다!

2023-01-25 06:25 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/objects.py
> +    for obj in context.selected_objects:
(워니님 과 대화 결과) 현재 제가 구현한 move, scale, rotate가 cube가 아닌 모든 것들을 조정할 수 있어서 selected_objects 를 쓰는게 맞고 대신 move cube, scale cube, rotate cube 였던 패널 명칭을 그냥 move, scale, rotate로 바꾸기로 했습니다.

2023-02-02 08:37 UTC, sdkfile commented
자 그럼 온보딩 프로젝트는 닫도록 하겠습니다~ @HaYeonKim00

2023-02-02 08:37 UTC, closed without merging