Feature/abler to acon3d
ACON3D/blender pull request #283
Opened 2023-01-25 09:47 UTC by HaYeonKim00

## 관련 링크
[링크](URL)

## 발제/내용

- 

## 대응

### 어떤 조치를 취했나요?

-

2023-01-26 06:23 UTC, sdkfile requested changes
잠깐 훑어보고 보이는 수정사항 남겼습니다. 추가할 내용 있으면 나중에 더 추가해볼게요! @HaYeonKim00

2023-01-26 06:23 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> +        import webbrowser
이렇게 하게 되면 execute할 때마다 webbrowser 모듈을 import 해와서 비효율적인 것 같아요. 파일 서두에 넣는게 어떨까요?

2023-01-26 06:26 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        import webbrowser
넵 좋습니다

2023-01-26 07:00 UTC, Youdiie reviewed
language 이외엔 기능 잘 작동합니다. 고생하셨습니다
추가적으로 UI에서 다른 버튼과 차이를 두면 어떨까요? (예 : 검색 UI 아래 선을 추가 or 검색만 토글 목록(>)으로 넣기) @sdkfile

2023-01-26 07:04 UTC, sdkfile commented
> language 이외엔 기능 잘 작동합니다. 고생하셨습니다 추가적으로 UI에서 다른 버튼과 차이를 두면 어떨까요? (예 : 검색 UI 아래 선을 추가 or 검색만 토글 목록(>)으로 넣기) @sdkfile

@Youdiie 이번에는 다른버튼들과 큰 차이를 두지 않고도 에이콘에서의 구매기여 검증이 목표였어서 UI는 다른 버튼들과 톤앤매너가 비슷하도록 최대한 평이하게 가는 방향으로 작업하였습니다. 현상유지 방향이 더 좋을 것 같습니다!

2023-01-26 07:05 UTC, Youdiie commented
> @Youdiie 이번에는 다른버튼들과 큰 차이를 두지 않고도 에이콘에서의 구매기여 검증이 목표였어서 UI는 다른 버튼들과 톤앤매너가 비슷하도록 최대한 평이하게 가는 방향으로 작업하였습니다. 현상유지 방향이 더 좋을 것 같습니다!

테스트도 같이 들어가는 기능이군요! 감삼당

2023-01-26 07:10 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        lang = bpy.context.preferences.view.language.split("_")[0]
넵!! 변경했습니다 감사합니다

2023-01-26 07:13 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +    bl_label = ""
row.operator(text="")에 넣으면서 비워두었습니다! 지우겠습니다

2023-01-26 07:14 UTC, JJong84 requested changes
리뷰 남겨드렸습니다~

2023-01-26 07:14 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> +        existing_lang = ["ko", "en", "ja", "zh"]
저희 `locales.py` 라는 파일에서 현 리스트 `supported_locales` 라는 이름으로 관리하고 있습니다! 그 부분에서 가져오는 게 관리하기 쉽고 중복을 없앨 수 있을 것 같습니다.
@HaYeonKim00

2023-01-26 07:18 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        existing_lang = ["ko", "en", "ja", "zh"]
넵! 수정했습니다!

2023-01-26 07:20 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +    bl_label = ""
아 bl_label을 지우면 error가 발생하네요. 그러면 그 row.operator(text="")와 동일한 값으로 해두겠습니다

2023-01-26 07:24 UTC, Youdiie approved these changes
큐브 PR에서 어프룹을 안드렸네요.. 첫 어프룹 드립니다! 고생하셨어요

2023-01-26 07:31 UTC, JJong84 requested changes

2023-01-26 07:31 UTC, JJong84 commented on release/scripts/startup/abler/general_tab/general.py
> +        lang = bpy.context.preferences.view.language.split("_")[0]
아래 조건에서 lang 를 다시 설정해주기 때문에 else 로 위 조건 빼면 좋을 것 같습니다!

2023-01-26 07:36 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        lang = bpy.context.preferences.view.language.split("_")[0]
넵!

2023-01-27 01:09 UTC, JJong84 approved these changes
어프룹드립니다~ 고생하셨습니다!

2023-02-02 08:01 UTC, sdkfile requested changes
다른 코드는 다 확인했는데, URL 부분이 개선의 여지가 있어보여서 리뷰 코멘트 달았습니다.

2023-02-02 08:01 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> +        anchor.url = f"https://www.acon3d.com/{lang}/toon?utm_source=abler&utm_medium=program&utm_campaign=abler2acon&utm_content=button_CTA&utm_term=none"
여기서 url들끼리 겹치는 부분이 많아서 가독성을 위해 + 유지보수 가능성을 위해서 program, abler2acon, button_CTA이렇게 세개의 스트링은 따로 빼두고 f-string으로 넣어주면 좋을 것 같아요.

2023-02-02 08:06 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        anchor.url = f"https://www.acon3d.com/{lang}/toon?utm_source=abler&utm_medium=program&utm_campaign=abler2acon&utm_content=button_CTA&utm_term=none"
넵 반영해서 다시 커밋하겠습니다

2023-02-02 08:14 UTC, HaYeonKim00 commented on release/scripts/startup/abler/general_tab/general.py
> +        anchor.url = f"https://www.acon3d.com/{lang}/toon?utm_source=abler&utm_medium=program&utm_campaign=abler2acon&utm_content=button_CTA&utm_term=none"
추가했습니다!

2023-02-02 08:33 UTC, sdkfile approved these changes

2023-02-02 08:38 UTC, merged