파일명 뒤에 공백이 들어가지 않게 함
ACON3D/blender pull request #289
Opened 2023-01-31 08:02 UTC by HaYeonKim00

## 관련 링크
[공백 포함 폴더명으로 저장하는 오류 발생 후, 고품질 렌더를 연속으로 했을 때 발생하는 에러 - 테스크 카드](https://www.notion.so/acon3d/e7a8a6575b8e4545a825d117407cc43e)

## 발제/내용
- 

## 대응

### 어떤 조치를 취했나요?
- `basename.rstrip()`으로 파일명 뒤에 오는 공백이 없도록 함.(저장할 때, 랜더한 후)

2023-02-13 02:25 UTC, sdkfile requested changes

2023-02-13 02:25 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +            self.basename = self.basename.rstrip()
이거 윗줄이랑 합쳐도 될 것 같아요
```python
self.basename = ".".join(self.basename.split(".")[:-1]).rstrip()
```

2023-02-13 02:25 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/render_control.py
> +                self.basename = self.basename.rstrip()
얘랑

2023-02-13 02:25 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> +        basename = basename.rstrip()
얘도

2023-02-14 04:14 UTC, sdkfile approved these changes

2023-02-16 04:40 UTC, Youdiie approved these changes

2023-02-16 05:51 UTC, merged