bler.warning_modal에서 self.layout이 없을 때 에러 발생
ACON3D/blender pull request #294
Opened 2023-02-07 06:45 UTC by HaYeonKim00

## 관련 링크
[abler.warning_modal에서 self.layout이 없을 때 에러 발생  - 에러 카드](https://www.notion.so/acon3d/abler-warning_modal-self-layout-d360a1e086f1473880df8b98ba176cc5)

## 발제/내용
- WM_MT_splash_modal의 draw() 함수에서 `self.draw_func(self.layout)`을 실행할 때 self.layout이 None이라 에러 발생

## 대응

### 어떤 조치를 취했나요?
- self-layout이 None인지 확인하는 if문 추가

2023-02-13 02:31 UTC, sdkfile requested changes

2023-02-13 02:31 UTC, sdkfile commented on release/scripts/startup/abler/warning_modal.py
> +        print(self.layout)
print문 빼주세용~

2023-02-14 04:16 UTC, sdkfile approved these changes

2023-02-16 04:43 UTC, Youdiie approved these changes

2023-02-16 05:52 UTC, merged