OS에서 직접 삭제한 파일 경로에 파일을 저장하려고 할때 발생하는 문제
ACON3D/blender pull request #295
Opened 2023-02-08 06:07 UTC by HaYeonKim00

## 관련 링크
[저장을 할 때 폴더에 접근하고, OS에서 삭제한 후에 저장을 실행하면 발생하는 문제 - 에러 카드](https://www.notion.so/acon3d/OS-ad6bad4ef5a44d839aa78bd9606534dd)

## 발제/내용
- 유저가 파일경로가 사라진 상태에서 파일을 저장하려고 할 때 에러가 발생함

## 대응

### 어떤 조치를 취했나요?
- 가장 최근에 저장한 디렉토리안에 untitled라는 새로운 파일을 생성 후, 그곳에 파일 저장

2023-02-13 02:34 UTC, sdkfile requested changes

2023-02-13 02:34 UTC, sdkfile commented on release/scripts/startup/abler/lib/import_file.py
> +            f.close()
`with`문이 끝났는데, f를 닫는게 의미가 없어보여요. 이 줄은 삭제하셔도 괜찮지 않을까요? + 추가적으로 문제 발생할 소지 있는 것 같음.

2023-02-14 04:17 UTC, sdkfile commented on release/scripts/startup/abler/lib/import_file.py
> +            self.filepath = os.path.join(recent_dir + "/untitled/" + basename)
f.close() 쓰신거 혹시 모르니 빌드해서 확인해보시고 말씀해주세요 @HaYeonKim00

2023-02-14 06:09 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/import_file.py
> +            self.filepath = os.path.join(recent_dir + "/untitled/" + basename)
확인차: f.close() 있어도 없어도 빌드하고 테스트 결과 에러는 없었지만, with문 안에서는 f.close()가 없는게 원칙이라 빼는걸로

2023-02-16 04:43 UTC, Youdiie approved these changes

2023-02-16 04:55 UTC, JJong84 requested changes
@HaYeonKim00 확인 부탁드립니다!

2023-02-16 04:55 UTC, JJong84 commented on release/scripts/startup/abler/lib/import_file.py
> +    def check_filepath(self, save_check: bool):
save_check 가 항상 True 인 경우밖에 없는데 해당 변수가 필요할까요?
@HaYeonKim00

2023-02-16 05:16 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/import_file.py
> +    def check_filepath(self, save_check: bool):
앗 그렇네요 수정하겠습니다

2023-02-20 04:59 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/import_file.py
> +    def check_filepath(self, save_check: bool):
@JJong84 확인부탁드립니다!

2023-02-20 05:07 UTC, JJong84 approved these changes
@HaYeonKim00 제가 요청드린 부분 고쳐진 것 확인했고 어프룹드리겠습니다~

2023-02-20 11:27 UTC, sdkfile approved these changes

2023-02-21 00:00 UTC, merged