grid_on_when_selected에서 selected_objects가 없을 때 방지코드 추가
ACON3D/blender pull request #299
Opened 2023-02-15 01:17 UTC by HaYeonKim00

## 관련 링크
[grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생 - 에러 카드](https://www.notion.so/acon3d/grid_on_when_selected-selected_objects-425a307e30874400bf02ff14b3966a66?pvs=4)

## 발제/내용
- 

## 대응

### 어떤 조치를 취했나요?
-

2023-02-15 08:07 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    if bpy.context.selected_objects is not None:
바다코끼리 사용해보심을 추천드림다

2023-02-16 04:45 UTC, Youdiie requested changes

2023-02-16 04:45 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    if selected := bpy.context.selected_objects:
변수명에 ed는 잘 붙이지 않습니다. 단어로 변경 부탁드릴께요

2023-02-16 04:50 UTC, JJong84 commented on release/scripts/startup/abler/pref.py
> +    if selected := bpy.context.selected_objects:
boolean 값이니, is_selected 같은 형식으로 가도 괜찮을 것 같습니다~

2023-02-16 05:17 UTC, sdkfile approved these changes
그 이외의 것은 없습니다~

2023-02-16 05:17 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    if selected := bpy.context.selected_objects:
그냥 `selected_objects`로 가도 될것 같습니다

2023-02-20 05:00 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    if selected := bpy.context.selected_objects:
@sdkfile 변경했습니다!

2023-02-20 11:23 UTC, sdkfile commented
@Youdiie 이거 확인하시고 리뷰 남겨주셔야 할듯합니다~

2023-02-20 11:25 UTC, Youdiie approved these changes
어프룹임니다~

2023-02-21 00:01 UTC, merged

2023-02-21 06:30 UTC, HaYeonKim00 commented
<img width="795" alt="Screenshot 2023-02-21 at 3 23 37 PM" src="https://user-images.githubusercontent.com/76549884/220264658-47a772f5-d14c-4574-9e86-4dbfe452e434.png">
show_grid가 if문 안에서 선언되서 발생하는 문제인데, grid 테스팅만 하고 이 에러는 놓친거 같습니다.
근데 다시 확인해보니 그냥 if문 없이 show_grid = len(bpy.context.selected_objects) > 0 이렇게 하면 될 것 같은데 확인차 질문드립니다.

2023-02-22 08:27 UTC, habijung commented
@HaYeonKim00 위에 말씀하신 문제 해결 되셨을까요?!

2023-02-22 08:49 UTC, HaYeonKim00 commented
> @HaYeonKim00 위에 말씀하신 문제 해결 되셨을까요?! 아니면 함수 내에서 `show_grid` 기본값만 정해도 될 것 같아요.
> 
> ```python
> @persistent
> def grid_on_when_selected(dummy):
>     show_grid = False
>     if selected_objects := bpy.context.selected_objects:
>         ...
> ```

넵!! 스듴님도 같은 피드백 주셔서 [새로운 테스크](https://github.com/carpenstreet/blender/pull/302)에 반영했습니다!