Active Object가 없는데 오브젝트의 type속성에 접근하려는 문제
ACON3D/blender pull request #300
Opened 2023-02-15 04:27 UTC by HaYeonKim00

## 관련 링크
[Active object가 없는데 type에 접근하는 문제 - 노션 카드](https://www.notion.so/acon3d/Active-object-type-34991dc0f3244f7e883e066924bf0048?pvs=4)

## 발제/내용
-`add_group_list_from_collection()`함수에서 active object가 없는데 type값에 접근하려다 에러가 발생함.

## 대응

### 어떤 조치를 취했나요?
- obj의 존재여부를 확인하는 `If문` 추가

2023-02-16 04:46 UTC, Youdiie requested changes

2023-02-16 04:46 UTC, Youdiie commented on release/scripts/startup/abler/scene_tab/object_control.py
> +    if obj is not None:
is not None은 저희 코드 컨벤션과 달라 `if obj:`으로 변경 해주세요~

2023-02-16 05:16 UTC, sdkfile approved these changes
유디님 코멘트 이외의 것은 없어서 어프룹

2023-02-16 05:34 UTC, HaYeonKim00 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +    if obj is not None:
수정했습니다! is not None이 습관이 되어버렸나봅니다

2023-02-20 05:00 UTC, HaYeonKim00 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +    if obj is not None:
@Youdiie 변경했습니다!

2023-02-20 05:03 UTC, Youdiie approved these changes

2023-02-21 00:02 UTC, merged