런처 리팩토링
ACON3D/blender pull request #34
Opened 2022-04-27 05:43 UTC by Youdiie

진행중임니당

2022-05-02 04:33 UTC, sdkfile requested changes

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +        # TODO: 버튼 한번 클릭되면 비활성화 기능 넣기
self.download에 self.btn_update enabled 해제시키는 기능을 추가하면 되지 않을까용

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +        # 설치 파일 복사
```
"""
    test_function does blah blah blah.

    :param p1: describe about parameter p1
    :param p2: describe about parameter p2
    :param p3: describe about parameter p3
    :return: describe what it returns
""" 
```

이런 방식으로 함수에 코멘트 남기는게 어떨까요?

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +            # TODO: Launcher를 다시 실행할 수 있게 해주면?
https://github.com/ACON3D/blender/blob/4d634c65529fab4d9e4ff5276b946cd160354ede/launcher_abler/AblerLauncher.py#L406-L408

요부분이 다시 실행해주는 코드 아닌가용?

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
저는 c++버전에서는 이번에 그냥 os 별로 함수를 따로 안나누고 함수 내에서 구분하게 다 합쳐놨는데 그렇게하는게 어떨까요?

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +            '<html><head/><body><p>Utility to update ABLER to the latest version available at<br> \
이부분에 있는 html 스트링도 따로 상수로 빼놓는게 어떨까 싶습니다!

2022-05-02 04:33 UTC, sdkfile commented on launcher_abler/UpdateAbler.py
> +def check_abler(dir_, installedversion) -> tuple:
여기서 -> tuple 보다는
`from typing import Tuple`을 사용하시고 `def check_abler(dir_, installedversion) -> Tuplep[bool, str]` 이런식으로 타이핑 써주시면 좋을 것 같습니다!

2022-05-02 04:46 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +        # TODO: 버튼 한번 클릭되면 비활성화 기능 넣기
넵 self.download에 내용 추가하면 될거 같습니다!

2022-05-02 04:50 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
처음에 저희도 그렇게 생각했었는데 각 os별로 동작하는 방식이 너무 상이해 하나의 함수는 하나의 동작만 하는 단일 원칙 책임을 따르는게 좋다고 생각했습니다!

2022-05-02 04:51 UTC, Youdiie commented on launcher_abler/UpdateAbler.py
> +def check_abler(dir_, installedversion) -> tuple:
오호 타입을 tuple안에 넣는 방식도 있군요! 저렇게 변경해보겠습니닷

2022-05-02 04:59 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
약간 애매한 것 같아요 단일 원칙 책임에서 "하나의 동작"으로 정의될만한 것이 사실 "실행" 으로 가면 합치는게 좋을 것 같기도 하고...

저는 이렇게 작업하긴 했어요
``` cpp
void MainWindow::exec()
{
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
  qint64 pid;
  QProcess::startDetached(ut->info->getPath() + "/blender.exe",
                          {},
                          QStandardPaths::writableLocation(QStandardPaths::HomeLocation),
                          &pid);
  QCoreApplication::quit();
#elif __APPLE__
  qint64 pid;
  QProcess::startDetached(
      "open",
      {MainWindow::utility->info->getPath() + "/ABLER.app/Contents/macOS/ABLER"},
      QStandardPaths::writableLocation(QStandardPaths::HomeLocation),
      &pid);
  QCoreApplication::quit();
#elif __linux__
  qint64 pid;
  if (test_arg)
    QProcess::startDetached("open",
                            {ut->info->getPath() + "/ABLER.app", "--test"},
                            QStandardPaths::writableLocation(QStandardPaths::HomeLocation),
                            &pid);
  else
    QProcess::startDetached("open",
                            {ut->info->getPath() + "/ABLER.app"},
                            QStandardPaths::writableLocation(QStandardPaths::HomeLocation),
                            &pid);
  QCoreApplication::quit();
#endif
}
```

2022-05-02 05:18 UTC, seungha-kim reviewed
커밋이 46개 ㅠㅠ 고생 많으셨습니다!

한 가지 아쉬운 것은 한 번의 리팩토링으로 많은 목표를 달성하려고 했다는 점인데, diff 가 클수록 코드리뷰 & 테스트하기 어렵기도 하고, "더 좋은 코드"라는 기준도 시간이 지남에 따라 (사람이 성장하든, 프로젝트가 성장하든) 바뀌거든요. 그래서 같은 방식이라면 세 달 뒤쯤에 다시 리팩토링을 했을 때 또 diff 가 큰 리팩토링을 하게 될 수도 있습니다.

그래서 앞으로는 한 번의 리팩토링에서는 한 가지 문제만 해결해보는 쪽으로 작업해보는게 어떨까 제안드립니다!

2022-05-02 05:18 UTC, seungha-kim commented on launcher_abler/UpdateLauncher.py
> +if not os.path.isdir(get_datadir() / "Blender/2.96/updater"):
`디렉토리 있는지 확인하고, 없으면 만들고, 있으면 아무것도 안 한다` 를 한 줄에 할 수 있는 방법이 있어서 달아놓습니다! (필수는 아니라고 생각)

https://ponyozzang.tistory.com/437

글의 맨 마지막 부분입니다

2022-05-02 05:18 UTC, seungha-kim commented on launcher_abler/UpdateAbler.py
> +    f.close()
필요없는 close

2022-05-02 05:18 UTC, seungha-kim commented on launcher_abler/UpdateAbler.py
> +if not os.path.isdir(get_datadir() / "Blender/2.96/updater"):
요기도 os.makedirs 써서 한 줄로 줄일 수 있겠네요

2022-05-02 05:18 UTC, seungha-kim commented on launcher_abler/AblerLauncherUtils.py
> +class StateUI(Enum):
오 Enum 쓰는 것 좋네용

2022-05-02 05:18 UTC, seungha-kim commented on launcher_abler/UpdateLauncher.py
> +        elif sys.platform == "darwin":
launcher_abler 프로젝트는 현재 윈도에서만 쓰이는거라 맥/리눅스 관련 코드는 궁극적으로는 삭제되어야 한다고 생각하고 있었는데 맞을까요?

2022-05-02 05:28 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
C++ 쪽이 상대적으로 라인 수가 많지 않아서 이렇게 해도 크게 이상하지 않은 반면, 파이썬에서는 라인 수가 좀 더 많아서 쪼개는게 더 자연스러운 것 같아요

2022-05-02 05:34 UTC, habijung commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
그런데 저는 스듴님 방법에 동의하는데, 결국 "실행"이라는 동작을 수행하는 함수 내에서 플랫폼 별로 구현 방법이 다르기 때문이라 하나로 합치는게 어떨까? 하고 생각했습니다.

2022-05-02 05:45 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
호호 만약에 그 기준을 적용한다면 멀티플랫폼을 지원해야 하는 함수들 내부에 if/else 가 난무하게 될겁니당!

결국은 if/else 를 어떤 차원에 어떻게 둘 것인가 하는 문제인데, "실행 플랫폼" 이라는 조건은 프로그램 실행 시점에 딱 한 번만 평가해도 되는 조건이라, 이것 때문에 if/else 가 많아지는 것은 좋지 않게 느껴져요.

보통 "이루고자 하는 목적은 같은데 플랫폼마다 방법이 다른 경우" 에는 

- "목적"을 추상클래스로 만들고, 
- 플랫폼별로 각자의 방법대로 구현해놓은 자식 클래스를 구현하고,
- 프로그램 시작 시에 딱 한번의 if/else 로 실행 플랫폼에 맞는 클래스를 생성

하는게 best practice인 것 같아요.

2022-05-02 05:51 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
근데 제가 말한거를 꼭 했으면 좋겠다거나 이번에 적용했으면 좋겠다고 말하는 거는 아닙니다 ㅠㅠ 이 PR은 가급적 더 길어지지 않는게 좋을 것 같아요

2022-05-02 06:48 UTC, habijung commented on launcher_abler/AblerLauncher.py
> +            # TODO: Launcher를 다시 실행할 수 있게 해주면?
@sdkfile 
어떨때는 재실행 되다가 어떨때는 안되다가 해서 파악해보니, 윈도우에서는 **관리자 권한** 모드에 따라서 해당 부분의 실행 여부가 달라졌습니다.
테스트를 할 때, 터미널을 관리자 권한으로 실행하는 것에 유의해서 진행하면 될 것 같습니다.
관련 내용은 런처 QA에도 다룰 예정입니다!

2022-05-02 06:52 UTC, habijung commented
@seungha-kim 
리팩토링 범위에 대해서 말씀해주셨는데, 제가 이해하기로는 큰 단위의 리팩토링을 진행한다고 해도 세분화된 목적에 따라서 작은 단위로 쪼개서 여러개의 PR로 남기는게 좋을 것 같다는 말씀이실까요?

2022-05-02 06:56 UTC, sdkfile commented on launcher_abler/UpdateLauncher.py
> +        elif sys.platform == "darwin":
네네 맞긴 하네요! 그냥 빼도 될 듯 하네용

2022-05-02 07:00 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
>      def exec_windows(self):
넵 그게 좋을 것 같습니당 👍

2022-05-02 07:35 UTC, seungha-kim commented
> @seungha-kim 리팩토링 범위에 대해서 말씀해주셨는데, 제가 이해하기로는 큰 단위의 리팩토링을 진행한다고 해도 세분화된 목적에 따라서 작은 단위로 쪼개서 여러개의 PR로 남기는게 좋을 것 같다는 말씀이실까요?

넵. 만약에 큰 단위의 리팩토링을 어쩔 수 없이 해야하는 상황이라면, 단계별로 커밋이 잘 쪼개져있거나, 단계별로 PR이 쪼개져있어서 구분해서 이해하기 좋은 상태가 되면 좋을 것 같아요.

다만 저 개인적으로는 코드를 조금씩 점진적으로 고쳐나가는 리팩토링을 선호하는 편입니다!

2022-05-02 07:35 UTC, habijung commented on launcher_abler/UpdateLauncher.py
> +        elif sys.platform == "darwin":
아 그럼 platform 확인하는 과정을 윈도우만 남겨도 되겠군요? (@Youdiie)

2022-05-02 10:41 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +if not os.path.isdir(get_datadir() / "Blender/2.96/updater"):
20,21번째 줄을 합쳐서 os.makedirs(get_datadir() / "Blender/2.96", exist_ok=True) 하면 되겠군요!

2022-05-02 10:47 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +        elif sys.platform == "darwin":
아 맥은 C++ 써서 launcher_abler를 쓰겠군요! 그렇담 깔끔하게 삭제가시죠 @habijung

2022-05-02 10:49 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +        elif sys.platform == "darwin":
그러면 AblerLauncher.py의 done_abler 함수 내에서 에이블러를 실행하는 것도 exec_windows(self)만 남겨두는건 어떨까요?

2022-05-03 00:25 UTC, habijung commented on launcher_abler/AblerLauncherUtils.py
> +class StateUI(Enum):
스듴님께서 아이디어 주셨습니다! (@sdkfile)

2022-05-03 00:35 UTC, habijung commented on launcher_abler/AblerLauncher.py
> +        # TODO: 버튼 한번 클릭되면 비활성화 기능 넣기
```suggestion
    def setup_download_ui(self, entry, dir_name):
        ...
        # 중복 다운로드 방지를 위한 버튼 비활성화
        if dir_name == dir_:
            self.btn_update.setDisabled(True)
        else:
            self.btn_update_launcher.setDisabled(True)
```

해당 부분을 추가해서 업데이트 버튼 클릭하면 다운로드가 실행되면서 버튼이 비활성화 됩니다.
`config.ini` 업데이트 관련 내용은 조금 더 테스트해보고 새로운 PR로 진행할까 합니다.

2022-05-03 00:37 UTC, habijung commented on launcher_abler/AblerLauncher.py
> +        # 설치 파일 복사
마지막 주석 정리때 한번 해보겠습니다!

2022-05-03 06:15 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +        # 설치 파일 복사
영어로 코멘트 남기자는 말씀이실까요? 아님 """ """ 써서 일까요 @sdkfile

2022-05-03 06:40 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +        # 설치 파일 복사
아 당연히 `""" """` 말이죠 ㅋㅋ @Youdiie

2022-05-03 08:41 UTC, Youdiie commented
코멘트 달아주신 내용 업데이트해서 올려두었습니다!

2022-05-03 08:43 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
> +        thread.finishedEX.connect(self.finalcopy(dir_))
여기 에러나지 않나용?

2022-05-03 08:43 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
> +        thread.finishedEX.connect(self.finalcopy(dir_))
이렇게 하려면 finalcopy 에서 함수를 반환해야 할 것 같은 느낌

2022-05-03 08:47 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +        thread.finishedEX.connect(self.finalcopy(dir_))
댄님 요건 예전 commit 입니닷

2022-05-03 08:51 UTC, sdkfile requested changes
살짜쿵 수정사항 남겨봅니다...

 typing 쓸때는 전반적으로 다 생각해서 포괄적으로 타입을 쓰는게 좋을 것 같네요!

2022-05-03 08:51 UTC, sdkfile commented on launcher_abler/UpdateAbler.py
> +def check_abler(dir_, installedversion) -> Tuple[Enum, list]:
이 함수에서 `Tuple[Enum, Optional[list]]`가 반환되는 형태로 되어야 할 것 같아요. `finallist`가 `None`이었다가 나중에 할당되어서 `list`로 반환되네요

2022-05-03 08:51 UTC, sdkfile commented on launcher_abler/UpdateAbler.py
> +from typing import Tuple
여기서 `from typing import Tuple, Optional` 해주시면 Optional 사용 가능

2022-05-03 09:41 UTC, Youdiie commented on launcher_abler/UpdateAbler.py
> +def check_abler(dir_, installedversion) -> Tuple[Enum, list]:
아래 함수에도 Optioanl로 들어가는 부분 있어서 수정 같이 해주었습니당

2022-05-03 13:42 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
> +        thread.finishedEX.connect(self.finalcopy(dir_))
앗 그렇군용 ㅎㅎㅎ 잘못봤습니다!

2022-05-04 03:21 UTC, seungha-kim approved these changes
저는 미리 어프룹 눌러 놓슴다! 고생 많으셧어용

2022-05-06 06:17 UTC, sdkfile approved these changes

2022-05-06 06:18 UTC, sdkfile commented
어프룹 했습니다! @Youdiie @habijung 고생 많으셨습니다 :)

2022-05-06 06:18 UTC, merged