명령어로 런처 버전 업데이트
ACON3D/blender pull request #35
Opened 2022-05-04 10:55 UTC by habijung

## 관련 문서

- Notion : [명령어로 런처 버전 업데이트](https://www.notion.so/acon3d/cda3e9c96072483594d314e25b386df9)

## 진행 사항

- [x]  런처 업데이트 및 설치 테스트 필요성 인지
- [x]  명령어로 `config.ini` 수정 및 리셋
- [ ]  Case별로 `config.ini` 수정하고 런처 실행
- [ ]  Python 또는 명령어 없이 QA 자동화

## Usage

```bash
# ABLER Launcher 디렉터리로 이동
$ cd ~/blender/launcher_abler

# config.ini 파일 백업
$ python ConfigSelector.py --copy

# 명령어 실행으로 업데이트 테스트
# Update : Launcher O / ABLER O
$ python ConfigSelector.py --run --update launcher abler
```

## `ConfigSelector.py` 명령어

```bash
$ python ConfigSelector.py --help
usage: Parser [options]

ABLER launcher update test.

optional arguments:
  -h, --help            show this help message and exit
  --print, -p
  --copy, -c
  --reset, -r
  --remove
  --update [UPDATE ...], -u [UPDATE ...]
  --run
```

- `--print` : 자세한 사항 표시
- `--copy` : 현재 `config.ini` 를 백업. 백업 파일이 없으면 실행 필요
- `--reset` : 백업 파일로 `config.ini` 리셋 및 백업 파일 삭제
- `--remove` : 백업 파일 삭제
- `--update` : 업데이트할 조건 추가 (`abler` or `launcher`)
- `--run` : `AblerLauncher.exe` 실행

2022-05-06 07:37 UTC, sdkfile requested changes
사실 간단한 내용이긴 해서, 이 부분에 대해서 코멘트는 마이너한것 밖에 없습니다만, macOS에서도 사용될 수 있는 내용이 나중에 추가 되면 좋겠다는 생각도 있긴 하네용

2022-05-06 07:37 UTC, sdkfile commented on launcher_abler/ConfigSelector.py
> +        self.config_bak = os.path.join(self.updater, "config.bak")
보통은 backup 파일 네이밍을 `asdf.ghjk` -> `asdf.ghjk.bak`으로 많이들 하는 걸로 알고 있슴니당

2022-05-06 07:37 UTC, sdkfile commented on launcher_abler/ConfigSelector.py
> +            print("Already exists back-up file.")
마이너한거지만, `Back-up file already exists` 가 맞는 말 아닌가요 ㅋㅋ

2022-05-06 08:00 UTC, habijung commented on launcher_abler/ConfigSelector.py
> +            print("Already exists back-up file.")
그렇네요..ㅎㅎ 작문 실력을 들켜버렸습니다..

2022-05-06 08:07 UTC, habijung commented on launcher_abler/ConfigSelector.py
> +        self.config_bak = os.path.join(self.updater, "config.bak")
그렇게 하면 더 직관적이겠네요. 수정하겠습니다!

2022-05-09 02:39 UTC, habijung commented
> 사실 간단한 내용이긴 해서, 이 부분에 대해서 코멘트는 마이너한것 밖에 없습니다만, macOS에서도 사용될 수 있는 내용이 나중에 추가 되면 좋겠다는 생각도 있긴 하네용

macOS QT가 나오면 공용컴으로 열심히 테스트 해보겠습니다..!

2022-05-09 04:13 UTC, Youdiie approved these changes
test_server와 무관하게 동작하므로 요건 어프룹 가겠습니닷

2022-05-10 02:33 UTC, sdkfile approved these changes

2022-05-10 02:33 UTC, merged