런처 함수에 설명 주석 추가
ACON3D/blender pull request #39
Opened 2022-05-09 07:58 UTC by Youdiie

AblerLauncher, UpdateAbler, UpdateLauncher 내 함수마다 설명 주석 추가해주었습니다.
관련해서 노션 문서로 정리해두었습니다.
https://www.notion.so/acon3d/AblerLauncher-00ec858833e44694b53fba16035de209

2022-05-09 09:32 UTC, habijung approved these changes
정리하신 이미지 보기 너무 좋습니다!

2022-05-10 02:41 UTC, sdkfile requested changes

2022-05-10 02:41 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +        """Launcher 버전 확인 후 상태 결정"""
저는 개인적으로 이런 부분에는 typing이랑 (return값까지 모두 다) 파라미터와 리턴에 대한 내용도 좀 들어갔으면 좋겠어요

```python
    """
    Generate a camera name with the given name and index.
    :param name: the name of the camera
    :param i: index of the camera
    :return: full name of the camera
    """
```
![스크린샷 2022-05-10 오전 11 40 37](https://user-images.githubusercontent.com/43770096/167531977-18cf35f2-2382-41d3-bd7c-bff3f8883436.png)

2022-05-10 03:04 UTC, seungha-kim commented on launcher_abler/AblerLauncher.py
> +        """Launcher 버전 확인 후 상태 결정"""
앗 저는 요거 주석이 너무 길어져서 좋아하지 않는 편임당! 그리고 typing 제대로 하면 typing 으로 어느정도 해결되는 느낌도 있어용

2022-05-10 06:27 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +        """Launcher 버전 확인 후 상태 결정"""
스듴님과 함께 댄님 의견 보면서 일단 typing 넣어본 뒤에도 설명이 추가되는게 좋을거 같다고 판단되면 그때 추가하는걸로 얘기했습니다!

2022-05-10 06:30 UTC, Youdiie commented
함수내 파라미너, 리턴값 타입캐스팅 모두 추가해주었습니다!

2022-05-10 07:50 UTC, sdkfile submitted a review, later dismissed
dictionary 관련한 내용인데, 실제 안에 들어있는 데이터의 형태가 매우 가변적이면 넘어가주셔도 될 것 같습니다.

2022-05-10 07:50 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +    def update_config(self, entry: dict, dir_name: str) -> None:
저 여기서 어떤 dictionary 인지 `dict[str,str]` 의 형태로 나타낼 수 있을 것 같은데, 그렇게 해보는게 어떨까요?

2022-05-10 07:51 UTC, sdkfile requested changes
냉무

2022-05-10 07:51 UTC, sdkfile commented
> 냉무

https://github.com/ACON3D/blender/pull/39#pullrequestreview-967325309

이 내용 관련해서 실수로 어프룹해서 다시 롤백하고 새로 request change 남겨놓습니다

2022-05-10 08:02 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +    def update_config(self, entry: dict, dir_name: str) -> None:
https://api.github.com/repos/acon3d/blender/releases/latest
entry가 받는 녀석이 요 url인데 str, int, bool이 다 들어가 가변적이라 생각합니다!

2022-05-11 10:41 UTC, sdkfile approved these changes
좋아요~~

2022-05-11 10:41 UTC, sdkfile commented
테스트 끝나고 머지하겠슴다

2022-05-12 01:18 UTC, merged