런처 README 추가
ACON3D/blender pull request #42
Opened 2022-05-10 23:49 UTC by habijung

## 요약

런처 개발 환경 세팅 및 테스트 관련 `README.md`를 추가하였습니다.

## 항목

- 의존성 파일 `requirements.txt` 설치
- `res_rc.py` 파일 생성
- `ConfigUpdater.py` 사용법

2022-05-11 10:44 UTC, sdkfile requested changes

2022-05-11 10:44 UTC, sdkfile commented on launcher_abler/README.md
> +    - `AblerLauncher.exe` 가 숨긴 항목에 있고, 런처 업데이트 후 재실행을 위해서 관리자 권한이 필요
여기서 숨긴 항목이라는 뜻이 무슨 말인지 잘 모르겠어용

2022-05-11 10:44 UTC, sdkfile commented on launcher_abler/README.md
> +    - `AblerLauncher.exe` 가 숨긴 항목에 있고, 런처 업데이트 후 재실행을 위해서 관리자 권한이 필요
이거 빼고는 너무너무 괜찮습니다! 질문드린 부분 해결 되면 approve 하도록 하겠습니다! @habijung

2022-05-11 23:54 UTC, habijung commented on launcher_abler/README.md
> +    - `AblerLauncher.exe` 가 숨긴 항목에 있고, 런처 업데이트 후 재실행을 위해서 관리자 권한이 필요
@sdkfile 
좀 더 명확하게 수정했습니다! 감사합니다~

2022-05-17 07:36 UTC, sdkfile approved these changes

2022-05-17 08:08 UTC, Youdiie approved these changes

2022-05-17 08:08 UTC, merged