공지사항 작업 진행중
ACON3D/blender pull request #52
Opened 2022-05-19 05:07 UTC by sdkfile

공지사항 클라이언트 작업중입니다

2022-05-27 05:46 UTC, sdkfile commented
### 픽스 미팅 이후 수정사항
- 링크가 없는 공지사항에도 링크 버튼을 그리는 현상이 있어서 수정
- 서버가 올바르지 않은 답변을 보냈을 때 공지사항을 그리지 않도록 수정
- 서버가 5초이상 답변을 하지 않을 때에도 공지사항을 그리지 않도록 수정

2022-06-07 02:45 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +        (e.identifier, e.name, "", e.value)
wm.py에 구문 수정이 여러개 보이는데 black이 돈걸까요 아님 스듴님께서 정리하신 걸까요?

2022-06-07 02:45 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +                if i < 3:
i가 3보다 작을때만 내용을 그린다는게 이해가 안됩니다! 갯수 조절 때문인가요?

2022-06-07 02:45 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
self.ret = None일 때는 에러가 나지 않을까요? 따로 처리를 해줘야할거 같습니다

2022-06-07 02:45 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +    bl_label = ""
공지사항 맨 처음줄이 왜 생기나 했더니 빈 문자열 bl_label이 무조건 나와서 그렇네요
self.bl_label을 draw함수에서 업데이트(self.bl_label = s)해도 처음 빈 문자열이 공지사항에 나옵니다🥲

2022-06-07 04:38 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        (e.identifier, e.name, "", e.value)
이거 블랙 말고 clion 설정에서 돌아버린거 같아요... 허허 수정해볼게용

2022-06-07 04:41 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +                if i < 3:
위에 보면 `ret_list = list(reversed(ret_list))`로부터 최신순으로 정렬된 리턴값으로부터 시작합니다. 그래서 i <3이라는건 가장 최신의 3개의 notice 정보를 가지고 UI를 그려라 라는 얘기로 볼 수 있겠죠!

2022-06-07 04:41 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
저 무슨 말씀이신지 이해를 못했어용 조금 더 설명 부탁드려도 될까요?

2022-06-07 04:42 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +                if i < 3:
아하 최신순 정렬해서 3개만 가져온다는 거군요! 주석으로 내용 추가하면 어떨까요?

2022-06-07 04:42 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +                if i < 3:
아 넵넵 추가해볼게요! @Youdiie

2022-06-07 04:43 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
아 착각했네용 is not None 이라고 봤습니다 헤헤
`is None` 말고 `if not self.ret:` 으로 쓰면 어떨까요? 에이블러에서 not으로 표기하고 있어서

2022-06-07 04:44 UTC, sdkfile commented on release/scripts/startup/abler/credential_modal.py
> +    bl_label = ""
이건 어쩔 수 없지 않을까요... ㅠㅠ

2022-06-07 04:45 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
오케이 convention 따르도록 하겠습니당~

2022-06-07 05:51 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
여기서는 not 써도 될 것 같기는 한데 `x is None` 이랑 `not x` 랑 두 개의 의미가 꽤 다르기는 해요~

`x is None` 은 말 그대로 `x` 가 `None` 때에만 True 로 평가되고

`not x` 는 `x` 가 빈 문자열, 빈 리스트, False 등 `False`로 평가될 수 있는 값(Falsy)일 때에도 True 로 평가돼서

구분해서 쓰는게 맞을 것 같습니다!

저는 되도록 `not x` 는 x 가 진짜 `False` 이기를 기대하는 경우에만 쓰는 것 같아요.

2022-06-07 05:52 UTC, Youdiie approved these changes
말씀하신 내용 이외엔 기능 잘 작동됩니다! 고생많으셨습니닷

2022-06-07 05:53 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +        req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
네트워크 문제로 인해 `requests.get` 자체에서 예외가 발생할 수 있어서, 예외처리가 필요해 보입니당

2022-06-07 05:57 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            # request의 result를 뒤집어서 최신순으로 정렬
request의 result를 뒤집어서 최신순으로 정렬 -> 

이 부분 제가 미처 생각을 못했는데, 이렇게 하면 공지사항이 10개가 넘어가는 경우에 문제가 생기네용 ㅠ 예를 들어 1~15번 까지 공지사항이 있다고 할 때에,

- 기대 결과: 15, 14, 13 번이 보여야 함
- 실제 결과: API 에서 1페이지 (1~10번) 가 반환되기 때문에 10, 9, 8 번 공지사항이 보임

이렇게 되는 문제가 생깁니다.

이거 제가 오늘중으로 아예 서버쪽에서 최신순으로 보여주도록 고쳐놓을게요. 따라서 3100 라인의

```
ret_list = list(reversed(ret_list))
```

이 내용은 삭제해주시면 되겠습니다.

2022-06-07 05:58 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
흠냐뤼 맞네요 저도 is None 쓰면서 None인지 아닌지만 판단하기를 기대하고 썼던걸로 기억합니당.. 뇌 안거치고 수정했던것 같습니당 다시 돌리는게 맞겠네요!

2022-06-07 05:59 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            # request의 result를 뒤집어서 최신순으로 정렬
아아 지금은 페이지로 반환되는 중이었군요! 저는 그냥 전체 리스트 반환해주는줄 알고 있었습니당 이것도 수정해놓을게요~

2022-06-07 05:59 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
넵 감사합니다 :)

2022-06-07 06:11 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        (e.identifier, e.name, "", e.value)
반영 완료입니당

2022-06-07 06:11 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            if self.ret is None:
반영 완료입니당

2022-06-07 06:11 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
반영 완료입니당

2022-06-07 06:12 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            # request의 result를 뒤집어서 최신순으로 정렬
반영 완료!

2022-06-07 06:46 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            for i, notice in enumerate(ret_list):
내부에서 i를 쓰지 않고 3개를 자르기만 하고싶은 거라면 `for notice in ret_list[:3]:` 도 좋아보입니당

2022-06-07 06:48 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
앗... 방금 생각난건데 `draw` 안에 `requests.get` 이 들어오면 안 될 것 같습니다. 버튼에 마우스 포인터 올리는 등 화면을 다시 그려야 할 때마다 draw가 호출되는데, 그 때마다 `requests.get` 이 호출돼서 통신이 일어나겠네요

2022-06-07 06:49 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
혹은 `draw` 안에 들어오더라도 `requests.get` 이 딱 한 번만 실행되도록 하는 처리가 필요할 듯 하네요

2022-06-07 06:50 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            for i, notice in enumerate(ret_list):
하긴 이제 뒤집는 일도 없고 그러니 저게 깔끔하겠네용

2022-06-07 06:53 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
흠흠 맞네요... 그래서 느린것 같이 느껴졌던 순간이 있었군요... 생각도 못하고 있었네요 ㅠㅠ
그럼 글로벌로 사용할 수 있는 플래그가 필요하겠네요 살짝 고민해서 올려볼게용

2022-06-07 06:55 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
아 아니면 constructor 오버라이딩해서 해보는 방법도 괜찮을수도...?

2022-06-07 07:23 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            for i, notice in enumerate(ret_list):
작업 완료입니당

2022-06-07 07:24 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
__init__을 오버라이딩 해서 일단 올려봤는데요, 지금 딱히 생각나는 문제는 없는데 혹시 우려점이 있을까요?

2022-06-07 07:25 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
@seungha-kim 일단 __init__을 오버라이딩 해서 올려봤는데 생각하시는 우려점 있으실까용? 저는 딱히 생각은 안나네용!

2022-06-07 07:40 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
제 쪽에서 requests.get 바로 위에다가 print 찍어봤는데 버튼에 마우스 올릴 때마다 로그 찍히네용. draw만 매번 호출하는게 아니라 객체도 매번 새로 만드나봐요.

제 생각에는 생성자를 블렌더가 어떻게 쓰는지 API 문서에 제대로 안 나와있어서 여기에 의존하는 것보다는, 다른 방식이 좋을 것 같아요. 원상복구 고고? (hard reset + force push)

그리고 폭력적으로 글로벌 변수 만들어서 이런 식으로 해보는게 어떨까 함다 (실패하는 경우까지 고려)

```
# 글로벌 스코프
# 성공하면 ('SUCCESS', [...]) 실패하면 ('FAILED', None) 이 채워짐
notices = ('READY', None) 

def fetch_notices():
    # 전에 이미 성공/실패했으면 일찍 종료
    if notices[0] != 'READY':
        return
    ...
    req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
    if req is not None and req.status_code == 200:
        ...
        notices = ('SUCCESS', ret_list)
    else:
        # 실패한 경우 더 이상 통신을 하지 않게 하기 위함
        notices = ('FAILED', None)

class WM_MT_splash(Menu):
    def draw(self, context):
        ...
        fetch_notices()
        if notices[0] == 'SUCCESS':
            ... # 화면 그리기

```

2022-06-07 07:49 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
휴 객체까지 새로 만들줄이야... 킹받네요 ㅋㅋㅋ

넵 내일 원상복구하고 글로벌 변수 만들어서 깔끔하게 만들어볼게요 이미 밤 10시라 여긴..ㅋㅋ (notices status의 경우에는 enum으로 만들어도 깔끔하겠네요)

2022-06-07 23:42 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
원복 완료입니당

2022-06-08 02:44 UTC, habijung commented on release/scripts/startup/abler/credential_modal.py
> +    bl_label = ""
관련해서 제목의 글자 크기를 크게 해주면 예쁘게 보이지 않을까? 했지만 dialog box 의 글꼴은 찾기가 힘드네요 🥲

2022-06-08 04:11 UTC, habijung commented on release/scripts/startup/abler/credential_modal.py
> +                    row.label(text=s)
본문이 창의 왼쪽 모서리에 너무 붙어 있는 것 같아서 제목처럼 icon을 추가하면 어떨까요?
테스트 해보긴 했는데 `icon="BLANK1"` 로 빈칸을 추가하고 `textwrap.fill` 너비를 조금 더 늘리면 꽤 괜찮게 보이는 것 같습니다..!
그런데 텍스트 라인이 끊겨서 다음 라인으로 넘어가면 빈칸이 적용이 안되어서 고민이 됩니다.

### (변경 후) textwrap.fill = 150
<img width="567" alt="image" src="https://user-images.githubusercontent.com/52474700/172529414-c63a39fb-8526-428e-aa82-8ea386bd2ecd.png">

### (변경 전) textwrap.fill = 75
<img width="570" alt="image" src="https://user-images.githubusercontent.com/52474700/172529766-5e75ddd5-585b-44d5-ae13-aa10e811da5b.png">

2022-06-08 04:21 UTC, seungha-kim approved these changes
requests 관련 문제 없는 것 확인했습니다. 기능적인 필수 요소들은 모두 점검됐다고 판단하고 어프룹 하겠습니다! 고생하셨습니다!

2022-06-08 04:22 UTC, seungha-kim requested changes
앗 잠시... fetch_notices 에 try except 가 빠진 것 같아요

2022-06-08 04:29 UTC, sdkfile commented on release/scripts/startup/abler/credential_modal.py
> +                    row.label(text=s)
이거는 나중에 후속으로 가시죠~~

2022-06-08 04:30 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +    req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
@seungha-kim 여기에 try-catch 넣겠습니다 ㅠㅠ

2022-06-08 04:30 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +    req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
넵넵!

2022-06-08 04:31 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +    req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
아싸리 네트워크 일부러 끊고 한번 테스트해보는것도 좋을 것 같슴다

2022-06-08 04:36 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +    req = requests.get(f"https://cms.abler3d.biz/notices/?language={lang}", timeout=5)
@seungha-kim 찐막 찐찐막으로 업뎃 완료입니당

2022-06-08 04:37 UTC, habijung commented on release/scripts/startup/abler/credential_modal.py
> +                    row.label(text=s)
좋습니다!

2022-06-08 04:39 UTC, seungha-kim approved these changes
찐막 어프룹!

2022-06-08 04:40 UTC, habijung approved these changes
수고하셨습니다!!

2022-06-08 04:46 UTC, sdkfile commented
감사합니다!!

2022-06-08 04:47 UTC, merged