Active Object가 없을 때 오브젝트 설정 UI 변경
ACON3D/blender pull request #61
Opened 2022-05-27 05:50 UTC by Youdiie

<img width="220" alt="스크린샷 2022-05-27 오후 1 42 07" src="https://user-images.githubusercontent.com/87409148/170638146-337aa2cc-e507-4f17-a8c2-85e4824cf164.png">

@classmethod는 아예 오퍼레이터를 지워버리므로 draw 내부에서 Active Object가 없을 때에 대한 처리를 해주는 것으로 변경.
look at me에서 context.object로 조건문을 두면 선택된 개체가 없어도 버튼을 누를 수 있기 때문에 prop에선 선택된 개체가 없을 때 바로 안 보여야 유저가 헷갈리지 않아 조건문에서 context.selected_objects로 설정(해당 내용 코드 주석으로도 넣었습니다)

기능적으로 이상 없으면 번역 PR 추후에 올리겠습니다.

노션카드 : https://www.notion.so/acon3d/UI-f8ce6048da1e4636a11e1ca6d66b4aa0

2022-05-27 06:11 UTC, sdkfile commented
빌드 해봤고, 기능적으로는 문제 없는 것 확인했습니다! 번역PR 머지되고 나서 approve 할게요!

2022-05-27 06:37 UTC, habijung requested changes
1. 기능은 문제 없으나, 오브젝트 선택을 안했을 때 나만 바라보기 체크박스 스타일이 다른건 수정 가능한가요?

- 오브젝트를 선택하지 않았을 때,
<img width="162" alt="image" src="https://user-images.githubusercontent.com/52474700/170642777-840a49ba-cb39-478e-9d93-b6a0037f3732.png">

- 오브젝트를 선택했을 때,
<img width="159" alt="image" src="https://user-images.githubusercontent.com/52474700/170642799-d423fc82-7d72-4565-9a2f-917a2be0aaee.png">

2. 오브젝트를 삭제했을 때 (`context.object == None`) 는 "No Selected Object"가 잘 보입니다. 그런데 그냥 오브젝트 선택하고 선택 해제를 할 때는 `row.enabled = False` 만 되는데, 이때도 그냥 "No Selected Object"를 보여주는건 어떨까요?

2022-05-27 07:36 UTC, Youdiie commented
@habijung 
1. 위의 체크박스는 icon="CHECKBOX_DEHLT"로 들어간거고 아래는 prop.operator에서 자동으로 들어가는 UI라 동일하게 그리는건 어렵습니다.
2. 넵 좋습니다. 고렇게 수정해볼께용

2022-05-27 07:48 UTC, Youdiie commented
하비님 1번 내용을 듣고 다시 생각해보니 icon을 똑같이 그릴 수 없다면 select가 안돼있다는걸 유저에게 알려주는 icon으로 변경하는게 좋을거 같아 테스트 해보았습니다. 두 아이콘을 넣어봤는데 둘 중 어떤게 나을까요?
<img width="218" alt="스크린샷 2022-05-27 오후 4 46 02" src="https://user-images.githubusercontent.com/87409148/170654767-3239084e-ee1d-46ec-b022-5a8e78385320.png">

<img width="216" alt="스크린샷 2022-05-27 오후 4 45 09" src="https://user-images.githubusercontent.com/87409148/170654754-5ee95af6-e318-4d1c-8da7-5df5d5db11d2.png">

2022-05-27 07:58 UTC, habijung commented
> 하비님 1번 내용을 듣고 다시 생각해보니 icon을 똑같이 그릴 수 없다면 select가 안돼있다는걸 유저에게 알려주는 icon으로 변경하는게 좋을거 같아 테스트 해보았습니다. 두 아이콘을 넣어봤는데 둘 중 어떤게 나을까요?
> 
> <img width="218" alt="스크린샷 2022-05-27 오후 4 46 02" src="https://user-images.githubusercontent.com/87409148/170654767-3239084e-ee1d-46ec-b022-5a8e78385320.png">
> 
> 
> 
> <img width="216" alt="스크린샷 2022-05-27 오후 4 45 09" src="https://user-images.githubusercontent.com/87409148/170654754-5ee95af6-e318-4d1c-8da7-5df5d5db11d2.png">

만약에 바꾼다면, 저는 1번이 더 좋은 것 같습니다.

2022-06-02 06:05 UTC, Youdiie commented
저두 1번이 좋은거 같습니다! 오브젝트 선택해제 시 "No Selected Object" 보여주는 것과 체크박스 아이콘 1번으로 수정해서 올렸습니당

2022-06-03 02:29 UTC, habijung commented
> 저두 1번이 좋은거 같습니다! 오브젝트 선택해제 시 "No Selected Object" 보여주는 것과 체크박스 아이콘 1번으로 수정해서 올렸습니당

훨씬 통일성 있고 깔끔한 것 같습니다!

2022-06-03 02:30 UTC, habijung approved these changes

2022-06-03 05:49 UTC, seungha-kim approved these changes
"No Selected Object" 는 뭔가의 제목이라기 보다는 메시지 성격이 강하니 "No selected object" 로 고치는게 어떨까 합니다!

사소한 거라 요건 유디님 선택에 맡기고, 어프룹 하겠습니다!

2022-06-03 07:16 UTC, Youdiie commented
> "No Selected Object" 는 뭔가의 제목이라기 보다는 메시지 성격이 강하니 "No selected object" 로 고치는게 어떨까 합니다!
> 
> 사소한 거라 요건 유디님 선택에 맡기고, 어프룹 하겠습니다!

메시지 성격에 맞게 "No selected object"로 수정하고 머지가겠습니당

2022-06-03 07:16 UTC, merged