post_render 시 render_queue 빈 리스트인지 확인
ACON3D/blender pull request #74
Opened 2022-07-01 01:52 UTC by Youdiie

센트리에서 발견된 오류 핸들링입니다.
모종의 이유(유저가 에이블러 외 기능을 누른것으로 추정)로 render_queue가 빈 리스트에서 렌더가 동작해 오류가 발생해 render_queue가 빈 리스트인지 확인하는 코드 추가했습니다.

노션 문서 : https://www.notion.so/acon3d/post_render-render_queue-25a2c82563034d59881a1a35ec0c3b3b

2022-07-01 04:52 UTC, habijung approved these changes
어프룹입니다!

2022-07-05 05:48 UTC, sdkfile requested changes

2022-07-05 05:48 UTC, sdkfile commented on release/scripts/startup/abler/render_control.py
> +        if not self.render_queue:
여기서 render_queue가 None인것만 거르지 말고, render_queue 오브젝트는 있지만, 아무 엔트리도 없을 경우도 걸러줘야 할 것 같습니다.

2022-07-05 05:59 UTC, sdkfile approved these changes

2022-07-05 05:59 UTC, merged