튜토리얼 팝업 개발
ACON3D/blender pull request #76
Opened 2022-07-05 09:07 UTC by sdkfile

튜토리얼 팝업을 개발하는 PR입니다. 

@Youdiie 와 @sdkfile 의 협업을 위해서 draft로 PR을 팝니다

2022-07-05 09:17 UTC, sdkfile commented
아래 함수는 splash.png를 불러오는 함수입니다.
https://github.com/ACON3D/blender/blob/4506c1e938eb602af94662ce4c06e56473d42bb9/source/blender/windowmanager/intern/wm_splash_screen.c#L146-L187

여기에 splash.png가 하드코딩되어있는 부분을 파라미터로 바꿔주고, python에서 해당 파일을 파라미터로 전달할 수 있게 만들고, 그 operator를 감싸는 python UI panel을 작업하면 될 것 같습니다

2022-07-05 09:55 UTC, sdkfile commented
splash.png를 바꿔서 일단 빌드해봤더니 이런 결과가 나왔습니다. (사이즈 비율은 살짝 바꾸면 될 것 같긴 함)
![스크린샷 2022-07-05 오후 6 54 14](https://user-images.githubusercontent.com/43770096/177302351-bf619e44-329a-4c74-925f-a01fc5431802.png)

2022-07-11 11:51 UTC, sdkfile reviewed
얼추 제가 하고 싶은 내용을 담은 제안사항을 리뷰 형태로 적어봤습니다 @Youdiie

2022-07-11 11:51 UTC, sdkfile commented on source/blender/windowmanager/intern/wm_splash_screen.c
> +    mt = WM_menutype_find("WM_MT_splash_tutorial", true);
여기를
`mt = WM_menutype_find("WM_MT_splash_tutorial1", true);`

2022-07-11 11:51 UTC, sdkfile commented on source/blender/windowmanager/intern/wm_splash_screen.c
> +    mt = WM_menutype_find("WM_MT_splash_tutorial", true);
여기도
`mt = WM_menutype_find("WM_MT_splash_tutorial1", true);`

2022-07-11 11:51 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +class WM_MT_splash_tutorial(Menu):
이거를 parent 클래스로 하는 Panel 클래스를 3개 만들어서 각 튜토리얼별로 살짝은 다른 디자인을 (하지만 상당부분은 유지해서 코드 재사용 가능하게) 가질 수 있도록 해보는게 어떨까요?

2022-07-11 11:51 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +class WM_MT_splash_tutorial(Menu):
Next, Prev 등의 텍스트는 어차피 버튼에 덧씌울 수 있으니

2022-07-12 04:41 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +class WM_MT_splash_tutorial(Menu):
요건 기획셀에서 splash UI를 통일하기로 결정돼 적용안하기로 했습니다~

2022-07-14 05:53 UTC, Youdiie commented
<img width="1440" alt="스크린샷 2022-07-14 오후 2 26 54" src="https://user-images.githubusercontent.com/87409148/178907414-6676b0e5-ff2d-4b8c-957a-e1ebbcd89cd5.png">
<img width="1440" alt="스크린샷 2022-07-14 오후 2 27 11" src="https://user-images.githubusercontent.com/87409148/178907449-5ff12506-1ed7-4192-b5f2-1bb4857f8a71.png">

길고 길었던 튜토리얼 팝업 PR 갑니닷

1. wm_splash_screen.c 코드에서 `wm.splash_tutorial_1` / `wm.splash_tutorial_2` / `wm.splash_tutorial_3` 오퍼레이터를 만들었습니다. 각각은 wm.py에서 구현한 WM_MT_splash_tutorial 클래스 UI를 받아와서 이미지를 추가해 스플래시를 띄우는 오퍼레이터입니다. 이미지는 CMakeLists.txt에서 png 경로를 받아와 data_to_c 파일로 변환합니다. 요 세 오퍼레이터를 wm_operators.c와 wm.h에 등록해줍니다.
2. "Show ABLER Starts" 토글은 custom_properties에서 show_guide라는 프로퍼티입니다. update=에 `remember_show_guide` 함수를 달아 토글을 선택/해제하면 그 값을 쿠키 폴더인 2.96 폴더 내 "tutorial"이란 파일에 True/False를 저장합니다. 그리고 가이드를 띄우는 general.py 내 AconTutorialGuidePopUpOperator의 execute 함수에서 요 파일의 값을 읽는 `read_remembered_show_guide` 함수를 실행시켜 값을 저장하도록 합니다.
3. 에이블러 실행 시에도 tutorial 파일을 읽는 `read_remembered_show_guide`를 실행시켜 토글 값이 켜져 있다면 가이드를 보이도록 합니다.
4. 세 오퍼레이터의 스플래시는 버튼을 누르면 중복이 돼서 OK 버튼의 AconTutorialGuideCloseOperator내에서 execute에 절대경로 (50,50)으로 커서를 이동한 뒤 pyautogui를 사용해 더블클릭을 해주고 있습니다. 요렇게 스플래시 바깥에서 더블클릭을 하면 스플래시가 아무리 많이 겹쳐도 한꺼번에 꺼집니다.

스플래시가 중복으로 안띄우게 하는건 개발 일정이 늘어날 거 같아 이번턴에서 더블클릭으로 자르고 기획셀이나 CS에서 요청이 들어오면 추후 개발을 하는걸로 진행하겠습니다.

2022-07-18 05:57 UTC, seungha-kim commented on source/blender/windowmanager/intern/wm_splash_screen.c
> +/*
요기 주석 쓰려다 만 것 같은 느낌??

주석에 내용 채워주시면 좋을 것 같슴다

2022-07-18 06:01 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +        anchor = row.operator("wm.url_open", text="Go To Guide (Notion)", icon='URL')
제가 보기에도 (Notion) 이 들어가있는게 이상하긴 하네용!

2022-07-18 06:11 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +    def draw(self, context):
사소한 부분일 수는 있지만 wm.py 가 black 이 안 돌게 설정해놓은 파일이라 코드 컨벤션(따옴표 종류, 띄어쓰기 등)을 놓치신 것 같은데, "같은 파일에 있는 코드와는 컨벤션을 맞춘다"는 기준으로 손으로 맞춰주시는게 좋을 것 같아요.

2022-07-18 06:17 UTC, seungha-kim commented
리뷰어 입장에서 요구사항, 기대 시나리오를 유디님만큼 모르고 있기 때문에 코드만 보고서는 리뷰를 제대로 하기가 어렵네요!

이 PR 에서 구현이 잘 되었는지 검수하기 위해 무엇을 하면 되는지, 설명을 덧붙여주시거나 자료 링크들 걸어주세요~

2022-07-18 06:18 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +    def draw(self, context):
3196,3198줄 띄우는거 말씀이시죠? 
따옴표 종류는 다른부분이 어디인지 모르겠습니다!

2022-07-18 06:19 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +        anchor = row.operator("wm.url_open", text="Go To Guide (Notion)", icon='URL')
요건 기획셀에서 버튼명 정해지면 수정하겠습니다~

2022-07-18 06:28 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +    def draw(self, context):
아하... 이 파일이 원래 따옴표 쓰는게 개판이었네요 ㅋㅋㅋㅋ ㅠㅠ 따옴표는 넘어갑시다.

띄어쓰기는 3225 줄 말한거였어요.

```
row.prop(userInfo.ACON_prop,"show_guide",text="",icon="CHECKBOX_HLT",emboss=False,invert_checkbox=True,)
```

이 코드가

```
row.prop(userInfo.ACON_prop, "show_guide", text="", icon="CHECKBOX_HLT", emboss=False, invert_checkbox=True)
```

이렇게 되는게 맞지 않나 해서용

2022-07-18 06:29 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +            # 튜토리얼 가이드 토글 값 받아와 띄우기
이 코드는 주석이 없어도 의미가 명확하게 읽히기 때문에 (앞으로는) 주석이 없어도 괜찮지 않나 하는 생각이 듭니다!

2022-07-18 06:30 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +    # 자동로그인인 경우에도 modal 실행하도록 if문 제거
그렇다면 본래 if 문은 왜 있었던 걸까요? 본래 if 문을 써야했던 이유가 있었을 것 같아서 불안하네용 (저도 내려받아서 실행해보긴 했는데, 이유를 찾진 못했음)

2022-07-18 06:49 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +    # 자동로그인인 경우에도 modal 실행하도록 if문 제거
저도 당시 개발할때의 이유는 모르겠지만 acon3d.modal_operator를 로그인 성공시에만 띄우게 하려고 넣지 않았을까 추측해봅니다.
acon3d.modal_operator를 띄워도 로그인 성공시엔 return {"FINISHED"}로 넘어가기 때문에 필요가 없어 보입니다!

2022-07-19 04:39 UTC, seungha-kim approved these changes
설명의 4번(스플래시 한꺼번에 꺼지게 한 workaround)이 좀 찜찜해서 [이런 곳](https://www.notion.so/acon3d/e040151826314093aa3a6f682ed31794)에다가 적어놓으면 좋을 것 같아요. ~예를 들면 화면 크기를 줄였을 때 튜토리얼 스플래시가 한꺼번에 꺼지지 않는 문제 라던가?~ 창 크기 줄이면 튜토리얼 팝업이 따라서 줄어드는 것 확인했습니다! 이렇게 적지 않아도 될 것 같네요

그것 말고는 좋아보여서 어프룹 합니다!

2022-07-19 04:45 UTC, seungha-kim requested changes
앗 제 맥에서 OK 버튼 누르면, 첫 번째 눌렀을 때는 Accesibility 권한을 부여해달라는 창이 떴고 
두 번째부터는 이상한 곳이 클릭돼서 의도한 대로 동작하지 않는 문제가 있어요. 이 부분은 다시 봐야 할 것 같아요

---

이후 유디님과의 숏미팅에서 발견한 사항:

유디님 머신에서 잘 되는 것처럼 보였던 이유는, `시스템 설정 > 보안 및 개인정보 보호 > 손쉬운 사용` 에서 터미널에 권한 부여가 되어있었기 때문입니다. 사용자 입장에서는 ABLER 에 같은 권한설정을 해주지 않는다면 역시 동작하지 않으리라고 예상할 수 있어요.

제 머신에서는 터미널에 권한 부여가 안 되어있었기 때문에 문제가 발견된 거였음
<img width="780" alt="image" src="https://user-images.githubusercontent.com/767106/179669384-f12533b1-79e0-4458-965c-c9da8c8b47ef.png">

2022-07-19 05:08 UTC, seungha-kim commented
일단 오늘 중에 유디님이 "pyautogui를 통한 workaround를 적용하지 않고도, 스플래시 화면이 꺼지게 만들 수 있는 방법"을 찾아보기로 하셨어요.

2022-07-20 10:41 UTC, Youdiie commented
댄님께서 도움 주셔서 OK버튼으로 튜토리얼 스플래시 끄기 + 이미 켜져있는 스플래시 끄고 다른 가이드 띄우도록  wm.tutorial_guide_close + wm.splash_tutorial_1을 감싸주는 acon3d.tutorial_guide_1/2/3 새로운 오퍼레이터를 만들었습니다.

2022-07-21 05:00 UTC, seungha-kim approved these changes
폭력 어프룹!

2022-07-21 06:17 UTC, habijung reviewed
`wm_splash_screen.c` 에서 반복 작업이 많아서 뭔가 같은 동작은 함수로 만들 수 있지 않을까? 했는데, `UI_popup_block_invoke`에서 함수 자체를 하나의 인자로 받아야 해서 함수 내부에서 튜토리얼 번호에 따라서 케이스를 나눌 수 없군요..

동작 확인에 문제가 없는 것 확인했고, 긴 작업 너무 수고 많으셨습니다!

2022-07-21 06:17 UTC, habijung commented on release/scripts/startup/abler/general.py
> +    bl_label = "OK"
취소 버튼 번역을 하기 위해 `bl_translation_context = "*"`를 추가하는건 어떨까요?

2022-07-21 06:21 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +    bl_label = "OK"
요녀석 없이도 번역됩니다!
블렌더 문서에도 bl_translation_context 기능에 대한 설명이 없네요

2022-07-21 06:27 UTC, habijung commented on release/scripts/startup/abler/general.py
> +    bl_label = "OK"
오퍼레이터에서 늘 보던건데 없어서 섭섭했던 것 같습니다. 확인 감사합니다~

2022-07-21 06:30 UTC, habijung approved these changes
바로 어프룹 갑니닷!

2022-07-21 07:40 UTC, merged