ADD Custom ObjectAllSelectOperator
ACON3D/blender pull request #84
Opened 2022-07-18 06:24 UTC by JJong84

`ObjectAllSelectOperator` 를 추가하여, 키맵에서 기존에 사용되던 블렌더 내장 `object.select_all` 과 교체하였습니다.

<이슈>
keymap 파일 (`abler_defaults.py`) 에서 넣어주는 `properties` 를 오퍼레이터에서 사용하는 방법을 찾지 못해서, `invoke` 함수를 추가하여, 해당 함수에서 key event 별로 `action`을 나누고, `action` 에 따라 `execute` 시 동작을 분기하였습니다.

2022-07-18 07:29 UTC, Youdiie approved these changes

2022-07-18 07:29 UTC, Youdiie commented on release/scripts/startup/abler/object_control.py
> +            bpy.ops.object.select_by_type(False, type="MESH")
그룹 네비게이션이 Parent-Child 구조로 변경됐을 때 최상단 Parent가 Mesh가 아닐수도 있지 않을까 걱정이 드네요

2022-07-18 09:33 UTC, sdkfile commented on release/scripts/startup/abler/object_control.py
> +            bpy.ops.object.select_by_type(False, type="MESH")
어 아니에요 이거 EMPTY랑 MESH 둘다 포함해야할것 같습니다..!!!

2022-07-19 04:21 UTC, JJong84 commented on release/scripts/startup/abler/object_control.py
> +            bpy.ops.object.select_by_type(False, type="MESH")
둘 다 포함시켜서 커밋하였습니다!

2022-07-19 08:55 UTC, sdkfile requested changes
저기 이상한거 뺴고는 별다른 의견 없슴다

2022-07-19 08:55 UTC, sdkfile commented on release/scripts/startup/abler/object_control.py
> +        if (key_type == "A" and key_value == "DOUBLE_CLICK") or (
여기 뭔가 좀 이상하지 않나요? 키보드 이벤트에 value가 double click이 있는게... 좀 이상함다!

2022-07-19 08:59 UTC, JJong84 commented on release/scripts/startup/abler/object_control.py
> +        if (key_type == "A" and key_value == "DOUBLE_CLICK") or (
놀랍게도 블렌더 자체에서 빠르게 연속으로 일어나는 키보드 이벤트도 더블 클릭으로 사용하고 있었습니다..!
[github 링크](https://github.com/blender/blender/blob/master/release/scripts/presets/keyconfig/keymap_data/blender_default.py#L321)

2022-07-19 09:04 UTC, sdkfile commented on release/scripts/startup/abler/object_control.py
> +        if (key_type == "A" and key_value == "DOUBLE_CLICK") or (
오... 그렇다면 어프룹 갑니다

2022-07-19 09:04 UTC, sdkfile approved these changes

2022-07-19 09:13 UTC, merged