최근 파일 열기를 커스텀 오퍼레이터로 교체
ACON3D/blender pull request #89
Opened 2022-07-20 04:34 UTC by JJong84

믹스패널 트래킹을 위해 "최근 파일 열기"를 커스텀 오퍼레이터로 교체하였습니다.

기존 "최근 파일 열기" 기능과 최대한 디자인을 비슷하게 유지시켰습니다.

![기존](https://user-images.githubusercontent.com/39782865/179897526-a35f498f-ae47-411a-afc0-66fe74f00798.png)

![이번 브랜치](https://user-images.githubusercontent.com/39782865/179897643-7015da42-48d0-4b28-ac8d-5305ef1a1cee.png)

2022-07-20 07:40 UTC, sdkfile requested changes
이 내용 제외하고는 이견 없습니다. 다른분들 코드리뷰하기 좋게 빠른 적용만 되면 좋겠습니다~~ @JJong84

2022-07-20 07:40 UTC, sdkfile commented on release/scripts/startup/abler/general.py
여기 줄 띄운것두요

2022-07-20 08:20 UTC, JJong84 commented on release/scripts/startup/abler/general.py
위랑 같은 이슈입니다!

2022-07-20 08:31 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> -
변경하였습니다!

2022-07-21 02:53 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.recent_file_open"
<img width="378" alt="스크린샷 2022-07-21 오전 11 46 02" src="https://user-images.githubusercontent.com/87409148/180119268-52cec0aa-bba6-46dd-b13b-a961769da544.png">

docstring 안적으면 사진처럼 (undocumented operator)라고 뜹니다! 188번줄처럼 operator 설명 추가해주세용

2022-07-21 02:53 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +class BaseFileOpenOperator:
BaseFileOpenOperator를 따로 두지말고 FileOpenOperator의 execute 동작에 open_file 함수가 들어가고 FileRecentOpenOperator가 FileOpenOperator를 상속받아서 오버라이딩 하면 어떨까용

2022-07-21 04:06 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +class BaseFileOpenOperator:
FileOpenOperator 가 ImportHelper 라는 class 도 상속받고 있어서 따로 두었습니다..!

2022-07-21 04:14 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.recent_file_open"
워니님이랑 함께 살펴본 결과 파일 경로에 파일이 없는 경우 에러로 (undocumented operator)가 뜹니다. 워니님께서 에러처리 추가로 해주시기로 얘기됐습니다!

2022-07-21 04:24 UTC, habijung reviewed
궁금한 부분 남겼습니다!

2022-07-21 04:24 UTC, habijung commented on release/scripts/startup/abler/general.py
>              tracker.file_open()
트래커가 `BaseFileOpenOperator` 에 있다는 것은, file open이나 file recent open을 굳이 구분하지 않고 같은 file open 으로 트래킹한다는 말씀이시죠?

2022-07-21 04:24 UTC, habijung commented on release/scripts/startup/bl_ui/space_topbar.py
> +class ACON3D_TOPBAR_MT_open_recent_files(Menu):
class명을 `TOPBAR_MT` 가 먼저 오는건 어떨까요?
오퍼레이터도 결국 `bpy.ops`로 오퍼레이터임을 먼저 알고 `acon3d`가 오는 것처럼, 비록 상속받는건 아니지만 `TOPBAR`에서 `Menu` 영역을 먼저 표기함이 더 좋을 것 같다는 생각이 들었습니다.
그래도 ACON3D가 더 중요하다면 그대로 가도 좋을 것 같습니다!

2022-07-21 04:28 UTC, Youdiie commented on release/scripts/startup/abler/general.py
>              tracker.file_open()
그러고보니 따로 트래킹할 수 있겠네요

2022-07-21 04:34 UTC, JJong84 commented on release/scripts/startup/abler/general.py
>              tracker.file_open()
네네 일단 같이 트래킹하는 조건으로 따로 구분했는데, 따로 구분해야한다면 수정이 필요할 것 같습니다!

2022-07-21 04:35 UTC, JJong84 commented on release/scripts/startup/bl_ui/space_topbar.py
> +class ACON3D_TOPBAR_MT_open_recent_files(Menu):
저도 TOPBAR_MT_ACON3D_open_recent_files 가 더 좋을 것 같습니다!

2022-07-21 04:39 UTC, JJong84 commented
보다보니까, 현 브랜치에서 최근 파일 목록이 있는 txt 파일이 갱신되지 않는 것 같아보이는 오류를 발견해서, 해당 부분까지 확인해보겠습니다..

2022-07-21 05:58 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.recent_file_open"
해당 부분 처리하였습니다!

2022-07-21 05:58 UTC, JJong84 commented on release/scripts/startup/bl_ui/space_topbar.py
> +class ACON3D_TOPBAR_MT_open_recent_files(Menu):
수정하였습니다.

2022-07-21 05:58 UTC, JJong84 commented
요청하셨던 변경사항 이외에,
최근 파일을 저장하는 파일을 찾을 수  없거나, 해당 파일에 아무것도 적혀있지 않을 때의 케이스도 추가로 처리해여 새로 커밋하였습니다.

[해당 커밋](https://github.com/ACON3D/blender/pull/89/commits/4f472df056385242d6084bf7dc2f1f12b19e26b1)

2022-07-21 06:04 UTC, Youdiie commented
> 요청하셨던 변경사항 이외에, 최근 파일을 저장하는 파일을 찾을 수 없거나, 해당 파일에 아무것도 적혀있지 않을 때의 케이스도 추가로 처리해여 새로 커밋하였습니다.
> 
> [해당 커밋](https://github.com/ACON3D/blender/pull/89/commits/4f472df056385242d6084bf7dc2f1f12b19e26b1)
> 
> 현존하는 문제점은, 최근 파일 열기를 커스텀 오퍼레이터로 교체하면서 최근 파일 리스트가 갱신이 되지 않는다는 문제가 있는데, 이 문제는 파일 열기, 파일 저장 등 기존 커스텀 오퍼레이터를 사용하던 부분에서도 원래 발생하던 문제라 새로운 이슈로 등록해 일괄적으로 처리하는 것은 괜찮을까요?

저는 찬성합니다~ 아예 다른 이슈로 봐야할거 같아요!

2022-07-21 06:08 UTC, Youdiie approved these changes

2022-07-21 06:31 UTC, JJong84 commented
기존 "최근 파일 열기" 기능과 최대한 디자인을 비슷하게 유지시키기위해 "File Not Found" 인 경우 filepath 도 보여주도록 수정했습니다..!

2022-07-21 08:40 UTC, merged