최근 파일 리스트 갱신 안되는 오류
ACON3D/blender pull request #96
Opened 2022-07-27 09:48 UTC by JJong84

[노션 링크](https://www.notion.so/acon3d/4c95cdda7e1f4144b767ca72e66e1fc7)

## 발제/내용

### **어떤 현상이 발생하고 있었나요? 가능하다면 스크린샷/영상을 첨부해주세요.**

- 블렌더와 다르게, 에이블러 내에서
Save as, Open File (v.0.2.3)
Save as, Open File, Open Recent (ABLER/main)
동작 시 최근 파일 리스트가 갱신되고 있지 않습니다.

위 동작들 모두, 저희가 커스텀 오퍼레이터를 만들어서 사용하는 부분들인데, 커스텀 오퍼레이터 실행 시 갱신이 되지 않는 이유를 확인해봐야할 것 같습니다.
![image](https://user-images.githubusercontent.com/39782865/181216861-67897f93-0d27-42af-bc05-f2c293a6b745.png)

|  | ABLER (as-is) | BLENDER (to-be) | Custom Operator 사용 여부 |
| --- | --- | --- | --- |
| Open (Recent) File | X | O (리스트 최상단) | O |
| Open (Recent) File - 변경사항 있을 때 (모달 띄워질 때) | O | O (리스트 최상단) | O |
| Open Recent - File Not Found | X | O (리스트에서 삭제) | O |
| Save as | X | O (리스트 최상단) | O |
| 파일로 프로그램을 여는 경우 | O | O (리스트 최상단) | X |

## 대응

### **재현 방법이 어떻게 되나요?**

- Save as, Open File (v.0.2.3)
Save as, Open File, Open Recent (ABLER/main) 동작 수행
- File → Open Recent 내의 파일들이 갱신되었는지 확인한다.

### 그래서 이 현상은 1)언제부터 2)어디에서 3)어떤 이유로 생겼나요?

- 기존 블렌더의 동작을 저희 커스텀 오퍼레이터로 교체하면서 생긴 이슈 같습니다.

### 어떤 조치를 취했나요?
- bpy.wm.open_mainfile, bpy.wm.save_as_mainfile 에 True 를 추가하였습니다.
- delete_path_from_recent_files 함수를 만들어서 파일이 없는 경우 최근 파일에서 지우도록 했습니다.

2022-07-27 09:58 UTC, JJong84 commented
Save as, File Load 할 때만 필요하다고 생각했는데, 
첫 Save 시에도 리스트 갱신해야할 것 같아서 해당 부분 다시 작업 후 PR Open 하겠습니다!

2022-07-28 02:51 UTC, JJong84 commented
@sdkfile @seungha-kim 
해당 부분 수정하여 Reopen 하였습니다.

2022-07-28 08:10 UTC, seungha-kim commented on release/scripts/startup/abler/general.py
> +                path for path in fin.read().splitlines() if path != target_path
경로 비교하는 코드가 들어가서 살짝 불안한데, 혹시 윈도우에서도 테스트 되었을까요?

2022-07-28 08:14 UTC, sdkfile requested changes
변경사항과 확인할 부분 포함하여 리뷰 했습니다.

2022-07-28 08:14 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +                path for path in fin.read().splitlines() if path != target_path
`history_path`가 상대경로로 나오는지 절대경로로 나오는지도 확인해봐야 한다고 생각합니다!

2022-07-28 08:14 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +            bpy.ops.wm.save_as_mainfile(
이 부분 변경 사항은 스코프와는 상관 없는 부분같습니다

2022-07-28 08:14 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +                bpy.ops.wm.save_mainfile(
마찬가지로 스코프와 상관 없는 변경사항같습니다

2022-07-28 08:14 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +                bpy.ops.wm.save_mainfile(
여기도 그렇군요

2022-07-28 08:17 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +                path for path in fin.read().splitlines() if path != target_path
윈도우에서 테스트해보겠습니다!

history_path 는 블렌더에서 항상 절대경로로 적고 있는 것 같습니다.

2022-07-28 08:18 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +            bpy.ops.wm.save_as_mainfile(
아래 True 가 추가되었습니다..!

2022-07-28 08:18 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +                bpy.ops.wm.save_mainfile(
이 부분도 마찬가지로 undo 값으로 True 가 추가되었습니다

2022-07-28 08:19 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +                bpy.ops.wm.save_mainfile(
이 부분도 마찬가지로 undo 값으로 True 가 추가되었습니다

2022-07-28 08:20 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +            bpy.ops.wm.save_as_mainfile(
앗 그러네요... 이건 제 미스 ㅎㅎ @JJong84

2022-07-28 08:28 UTC, JJong84 commented on release/scripts/startup/abler/general.py
> +                path for path in fin.read().splitlines() if path != target_path
윈도우에서도 항상 절대경로로 적고 있고, 모든 동작 다 정상적으로 동작하는 것 확인하였습니다.

2022-07-28 08:29 UTC, seungha-kim approved these changes
고생하셨습니다!

2022-07-28 08:39 UTC, sdkfile approved these changes

2022-07-28 08:40 UTC, merged